export const serverErrors = {
  SEM_ACESSO_OPCAO: "SEM_ACESSO_OPCAO",
  SEM_AUTENTICACAO: "SEM_AUTENTICACAO",
  COOKIE_EXPIROU: "COOKIE_EXPIROU",
  SEM_ACESSO_OPCAO_POR_LICENCIAMENTO: "SEM_ACESSO_OPCAO_POR_LICENCIAMENTO",
};