//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F3M.Oticas.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountingConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountingConfigurationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F3M.Oticas.Translate.AccountingConfigurationResources", typeof(AccountingConfigurationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuração para esta tabela já foi definida para o ano escolhido..
        /// </summary>
        public static string ConfigurationAlreadyExistWithSelectedYear {
            get {
                return ResourceManager.GetString("ConfigurationAlreadyExistWithSelectedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta, valor ou natureza não está preenchida..
        /// </summary>
        public static string ConfigurationHasInvalidLines {
            get {
                return ResourceManager.GetString("ConfigurationHasInvalidLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuração tem que ter pelo menos uma linha a débito e outra a crédito..
        /// </summary>
        public static string ConfigurationMustHaveAtLeastOneDebitAndCreditLine {
            get {
                return ResourceManager.GetString("ConfigurationMustHaveAtLeastOneDebitAndCreditLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuração tem que ter pelo menos uma linha..
        /// </summary>
        public static string ConfigurationMustHaveAtLeastOneLine {
            get {
                return ResourceManager.GetString("ConfigurationMustHaveAtLeastOneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tabela ou o tipo de documento não está preenchido..
        /// </summary>
        public static string TypeIsRequired {
            get {
                return ResourceManager.GetString("TypeIsRequired", resourceCulture);
            }
        }
    }
}
