//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F3M.Oticas.Translate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountingExportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountingExportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F3M.Oticas.Translate.AccountingExportResources", typeof(AccountingExportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar filtros.
        /// </summary>
        public static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condições.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Doc..
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Série.
        /// </summary>
        public static string DocumentSerie {
            get {
                return ResourceManager.GetString("DocumentSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de documento.
        /// </summary>
        public static string DocumentTypes {
            get {
                return ResourceManager.GetString("DocumentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuração não está definida para o tipo de documento/ano..
        /// </summary>
        public static string DocumentWithoutConfiguration {
            get {
                return ResourceManager.GetString("DocumentWithoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de fim.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor final.
        /// </summary>
        public static string EndValue {
            get {
                return ResourceManager.GetString("EndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terceiro.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimento exportado.
        /// </summary>
        public static string ExportedMovement {
            get {
                return ResourceManager.GetString("ExportedMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar ficheiro.
        /// </summary>
        public static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato exportação.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimento gerado.
        /// </summary>
        public static string GeneratedMovement {
            get {
                return ResourceManager.GetString("GeneratedMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar movimentos.
        /// </summary>
        public static string GenerateMovements {
            get {
                return ResourceManager.GetString("GenerateMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início.
        /// </summary>
        public static string InitDate {
            get {
                return ResourceManager.GetString("InitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inicial.
        /// </summary>
        public static string InitValue {
            get {
                return ResourceManager.GetString("InitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O movimento não está balanceado..
        /// </summary>
        public static string MovementNotBalanced {
            get {
                return ResourceManager.GetString("MovementNotBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos de conta não definidos..
        /// </summary>
        public static string TokensNotDefined {
            get {
                return ResourceManager.GetString("TokensNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
