'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class EstruturaMedicosTecnicos
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OticasTraducao.EstruturaMedicosTecnicos", GetType(EstruturaMedicosTecnicos).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Abreviatura.
    '''</summary>
    Public Shared ReadOnly Property Abreviatura() As String
        Get
            Return ResourceManager.GetString("Abreviatura", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Apelido.
    '''</summary>
    Public Shared ReadOnly Property Apelido() As String
        Get
            Return ResourceManager.GetString("Apelido", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cartão do Cidadão/BI.
    '''</summary>
    Public Shared ReadOnly Property CartaoCidadao() As String
        Get
            Return ResourceManager.GetString("CartaoCidadao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Código.
    '''</summary>
    Public Shared ReadOnly Property Codigo() As String
        Get
            Return ResourceManager.GetString("Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cor Fundo.
    '''</summary>
    Public Shared ReadOnly Property CorFundo() As String
        Get
            Return ResourceManager.GetString("CorFundo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cor Fundo 1ª Vez.
    '''</summary>
    Public Shared ReadOnly Property CorFundo1Vez() As String
        Get
            Return ResourceManager.GetString("CorFundo1Vez", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cor Texto.
    '''</summary>
    Public Shared ReadOnly Property CorTexto() As String
        Get
            Return ResourceManager.GetString("CorTexto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cor Texto 1ª Vez.
    '''</summary>
    Public Shared ReadOnly Property CorTexto1Vez() As String
        Get
            Return ResourceManager.GetString("CorTexto1Vez", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data de Nascimento.
    '''</summary>
    Public Shared ReadOnly Property DataNascimento() As String
        Get
            Return ResourceManager.GetString("DataNascimento", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Data de Validade.
    '''</summary>
    Public Shared ReadOnly Property DataValidade() As String
        Get
            Return ResourceManager.GetString("DataValidade", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Entidade 1.
    '''</summary>
    Public Shared ReadOnly Property Entidade1() As String
        Get
            Return ResourceManager.GetString("Entidade1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Entidade 2.
    '''</summary>
    Public Shared ReadOnly Property Entidade2() As String
        Get
            Return ResourceManager.GetString("Entidade2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Entidades e Médico / Técnico.
    '''</summary>
    Public Shared ReadOnly Property EntidadeMedicoTecnico() As String
        Get
            Return ResourceManager.GetString("EntidadeMedicoTecnico", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fotografia.
    '''</summary>
    Public Shared ReadOnly Property Foto() As String
        Get
            Return ResourceManager.GetString("Foto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to FotoCaminho.
    '''</summary>
    Public Shared ReadOnly Property FotoCaminho() As String
        Get
            Return ResourceManager.GetString("FotoCaminho", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loja.
    '''</summary>
    Public Shared ReadOnly Property Loja() As String
        Get
            Return ResourceManager.GetString("Loja", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Médico.
    '''</summary>
    Public Shared ReadOnly Property Medico() As String
        Get
            Return ResourceManager.GetString("Medico", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Médico / Técnico.
    '''</summary>
    Public Shared ReadOnly Property MedicoTecnico() As String
        Get
            Return ResourceManager.GetString("MedicoTecnico", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nº Cédula.
    '''</summary>
    Public Shared ReadOnly Property NCedula() As String
        Get
            Return ResourceManager.GetString("NCedula", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nº Contribuinte.
    '''</summary>
    Public Shared ReadOnly Property NContribuinte() As String
        Get
            Return ResourceManager.GetString("NContribuinte", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contribuinte.
    '''</summary>
    Public Shared ReadOnly Property NumContribuinte() As String
        Get
            Return ResourceManager.GetString("NumContribuinte", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nº Beneficiário 1.
    '''</summary>
    Public Shared ReadOnly Property NumeroBeneficiario1() As String
        Get
            Return ResourceManager.GetString("NumeroBeneficiario1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nº Beneficiário 2.
    '''</summary>
    Public Shared ReadOnly Property NumeroBeneficiario2() As String
        Get
            Return ResourceManager.GetString("NumeroBeneficiario2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Observações.
    '''</summary>
    Public Shared ReadOnly Property Observacoes() As String
        Get
            Return ResourceManager.GetString("Observacoes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sexo.
    '''</summary>
    Public Shared ReadOnly Property Sexo() As String
        Get
            Return ResourceManager.GetString("Sexo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem agenda.
    '''</summary>
    Public Shared ReadOnly Property TemAgenda() As String
        Get
            Return ResourceManager.GetString("TemAgenda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tempo por consulta.
    '''</summary>
    Public Shared ReadOnly Property Tempoconsulta() As String
        Get
            Return ResourceManager.GetString("Tempoconsulta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tipo.
    '''</summary>
    Public Shared ReadOnly Property Tipo() As String
        Get
            Return ResourceManager.GetString("Tipo", resourceCulture)
        End Get
    End Property
End Class
