'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class EstruturaCliente
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OticasTraducao.EstruturaCliente", GetType(EstruturaCliente).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Abaixo da Linha.
    '''</summary>
    Public Shared ReadOnly Property Abaixo_Linha() As String
        Get
            Return ResourceManager.GetString("Abaixo_Linha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Acima da Linha.
    '''</summary>
    Public Shared ReadOnly Property Acima_Linha() As String
        Get
            Return ResourceManager.GetString("Acima_Linha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adicionar linha abaixo.
    '''</summary>
    Public Shared ReadOnly Property Adicionar_Linha_Abaixo() As String
        Get
            Return ResourceManager.GetString("Adicionar_Linha_Abaixo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adicionar linha acima.
    '''</summary>
    Public Shared ReadOnly Property Adicionar_Linha_Acima() As String
        Get
            Return ResourceManager.GetString("Adicionar_Linha_Acima", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Aviso(s).
    '''</summary>
    Public Shared ReadOnly Property alerta_aviso() As String
        Get
            Return ResourceManager.GetString("alerta_aviso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Erro(s).
    '''</summary>
    Public Shared ReadOnly Property alerta_erro() As String
        Get
            Return ResourceManager.GetString("alerta_erro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Informação.
    '''</summary>
    Public Shared ReadOnly Property alerta_info() As String
        Get
            Return ResourceManager.GetString("alerta_info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirmação.
    '''</summary>
    Public Shared ReadOnly Property alerta_questao() As String
        Get
            Return ResourceManager.GetString("alerta_questao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A Enviar....
    '''</summary>
    Public Shared ReadOnly Property anexo_a_enviar() As String
        Get
            Return ResourceManager.GetString("anexo_a_enviar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Aplicar a todas.
    '''</summary>
    Public Shared ReadOnly Property aplicar_a_todas() As String
        Get
            Return ResourceManager.GetString("aplicar_a_todas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma localização com o código {0}.
    '''</summary>
    Public Shared ReadOnly Property armazens_localizacao_existente() As String
        Get
            Return ResourceManager.GetString("armazens_localizacao_existente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O armazém &quot;{0}&quot; já está definido no artigo..
    '''</summary>
    Public Shared ReadOnly Property artigos_armazem_existente() As String
        Get
            Return ResourceManager.GetString("artigos_armazem_existente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Até ao dia.
    '''</summary>
    Public Shared ReadOnly Property AteDia() As String
        Get
            Return ResourceManager.GetString("AteDia", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fechar Tabs - Atual.
    '''</summary>
    Public Shared ReadOnly Property campo_modulos_atual() As String
        Get
            Return ResourceManager.GetString("campo_modulos_atual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fechar Tabs - Todos.
    '''</summary>
    Public Shared ReadOnly Property campo_modulos_todos() As String
        Get
            Return ResourceManager.GetString("campo_modulos_todos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fechar Tabs - Todos menos este.
    '''</summary>
    Public Shared ReadOnly Property campo_modulos_todos_menos_este() As String
        Get
            Return ResourceManager.GetString("campo_modulos_todos_menos_este", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tudo menos a opção.
    '''</summary>
    Public Shared ReadOnly Property campo_modulos_tudo_menos_opcao() As String
        Get
            Return ResourceManager.GetString("campo_modulos_tudo_menos_opcao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Campos em Falta.
    '''</summary>
    Public Shared ReadOnly Property campos_em_falta() As String
        Get
            Return ResourceManager.GetString("campos_em_falta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} é inválido.
    '''</summary>
    Public Shared ReadOnly Property campos_invalidos() As String
        Get
            Return ResourceManager.GetString("campos_invalidos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} é obrigatório.
    '''</summary>
    Public Shared ReadOnly Property campos_obrigatorios() As String
        Get
            Return ResourceManager.GetString("campos_obrigatorios", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Campos Preenchidos.
    '''</summary>
    Public Shared ReadOnly Property campos_preenchidos() As String
        Get
            Return ResourceManager.GetString("campos_preenchidos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Esta pagina está em Adição/Alteração..
    '''</summary>
    Public Shared ReadOnly Property confirmacao_adicao_alteracao() As String
        Get
            Return ResourceManager.GetString("confirmacao_adicao_alteracao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Esta pagina está em Adição/Alteração, pretende fechá-la?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_adicao_alteracao_pagina() As String
        Get
            Return ResourceManager.GetString("confirmacao_adicao_alteracao_pagina", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Existem paginas em Adição/Alteração..
    '''</summary>
    Public Shared ReadOnly Property confirmacao_adicao_edicao() As String
        Get
            Return ResourceManager.GetString("confirmacao_adicao_edicao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Esta página está em Adição/Alteração, pretende cancelar as alterações efetuadas?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_adicao_edicao_cancelar() As String
        Get
            Return ResourceManager.GetString("confirmacao_adicao_edicao_cancelar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pretende cancelar as alterações efetuadas?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_cancelar_alteracoes() As String
        Get
            Return ResourceManager.GetString("confirmacao_cancelar_alteracoes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem a certeza que deseja fechar a opção?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_fecho_op() As String
        Get
            Return ResourceManager.GetString("confirmacao_fecho_op", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem a certeza que deseja terminar a sessão?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_logout() As String
        Get
            Return ResourceManager.GetString("confirmacao_logout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem a certeza que deseja marcar por defeito a lista personalizada {0}?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_marcarvista() As String
        Get
            Return ResourceManager.GetString("confirmacao_marcarvista", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pretende fechar todas as opções excepto a atual? .
    '''</summary>
    Public Shared ReadOnly Property confirmacao_modulo_excepto_atual() As String
        Get
            Return ResourceManager.GetString("confirmacao_modulo_excepto_atual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pretende fechar a opção atual excepto as outras?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_modulo_excepto_outros() As String
        Get
            Return ResourceManager.GetString("confirmacao_modulo_excepto_outros", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pretende fechar todas as opções?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_modulo_fecha_todos() As String
        Get
            Return ResourceManager.GetString("confirmacao_modulo_fecha_todos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pretende fechar todas as opções e deixar a opção atual?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_modulo_tab_opcao_atual() As String
        Get
            Return ResourceManager.GetString("confirmacao_modulo_tab_opcao_atual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem a certeza que deseja remover {0}?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_remover() As String
        Get
            Return ResourceManager.GetString("confirmacao_remover", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem a certeza que deseja remover a lista personalizada {0}?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_removevista() As String
        Get
            Return ResourceManager.GetString("confirmacao_removevista", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem alterações pendentes! Deseja continuar e perder a informação?.
    '''</summary>
    Public Shared ReadOnly Property confirmacao_sair() As String
        Get
            Return ResourceManager.GetString("confirmacao_sair", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Desselecionar as linhas todas.
    '''</summary>
    Public Shared ReadOnly Property DesselecionarLinhasTodas() As String
        Get
            Return ResourceManager.GetString("DesselecionarLinhasTodas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Detalhes do Anexo &quot;{0}&quot;.
    '''</summary>
    Public Shared ReadOnly Property detalhes_anexo() As String
        Get
            Return ResourceManager.GetString("detalhes_anexo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Existem alterações pendentes no artigo! Pretende guardar?.
    '''</summary>
    Public Shared ReadOnly Property deve_guardar_alteracoes() As String
        Get
            Return ResourceManager.GetString("deve_guardar_alteracoes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Alterar empresa.
    '''</summary>
    Public Shared ReadOnly Property empresas_alterarempresa() As String
        Get
            Return ResourceManager.GetString("empresas_alterarempresa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Atenção! Antes de prosseguir deve assegurar-se que tem todas as opções fechadas e todas as janelas do navegador com a aplicação aberta fechadas! Caso deseje continuar todas as opções serão fechadas, porém as janelas devem ser fechadas manualmente!.
    '''</summary>
    Public Shared ReadOnly Property empresas_avisoalterarempresa() As String
        Get
            Return ResourceManager.GetString("empresas_avisoalterarempresa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Carrregar outra empresa.
    '''</summary>
    Public Shared ReadOnly Property empresas_titulomudaempresa() As String
        Get
            Return ResourceManager.GetString("empresas_titulomudaempresa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O valor inserido é inválido..
    '''</summary>
    Public Shared ReadOnly Property erro_celula_invalida() As String
        Get
            Return ResourceManager.GetString("erro_celula_invalida", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Não existem áreas definidas para esta empresa..
    '''</summary>
    Public Shared ReadOnly Property erro_nao_existem_areas() As String
        Get
            Return ResourceManager.GetString("erro_nao_existem_areas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} &amp;lt.
    '''</summary>
    Public Shared ReadOnly Property erro_ocorrencia() As String
        Get
            Return ResourceManager.GetString("erro_ocorrencia", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Selecione uma empresa..
    '''</summary>
    Public Shared ReadOnly Property erro_selecione_empresa() As String
        Get
            Return ResourceManager.GetString("erro_selecione_empresa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to este anexo.
    '''</summary>
    Public Shared ReadOnly Property este_anexo() As String
        Get
            Return ResourceManager.GetString("este_anexo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Existem campos inválidos nas grelhas..
    '''</summary>
    Public Shared ReadOnly Property existem_campos_invalidos_nas_grelhas() As String
        Get
            Return ResourceManager.GetString("existem_campos_invalidos_nas_grelhas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Apagar favorito.
    '''</summary>
    Public Shared ReadOnly Property favorito_remover() As String
        Get
            Return ResourceManager.GetString("favorito_remover", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Favorito renomeado!.
    '''</summary>
    Public Shared ReadOnly Property favorito_renomeado() As String
        Get
            Return ResourceManager.GetString("favorito_renomeado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ficheiro anexado com sucesso!.
    '''</summary>
    Public Shared ReadOnly Property ficheiro_anexado_sucesso() As String
        Get
            Return ResourceManager.GetString("ficheiro_anexado_sucesso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Final do mês.
    '''</summary>
    Public Shared ReadOnly Property FinalMes() As String
        Get
            Return ResourceManager.GetString("FinalMes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Apenas são permitidas as extensões .jpg, .png, .gif..
    '''</summary>
    Public Shared ReadOnly Property foto_extensoes_permitidas() As String
        Get
            Return ResourceManager.GetString("foto_extensoes_permitidas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Não é permitido mais que 100 KB.
    '''</summary>
    Public Shared ReadOnly Property foto_tamanho_permitido() As String
        Get
            Return ResourceManager.GetString("foto_tamanho_permitido", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Não existe um registo selecionado.
    '''</summary>
    Public Shared ReadOnly Property grelha_sem_registo_selecionado() As String
        Get
            Return ResourceManager.GetString("grelha_sem_registo_selecionado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Não existem registos para apresentar.
    '''</summary>
    Public Shared ReadOnly Property grelha_sem_registos() As String
        Get
            Return ResourceManager.GetString("grelha_sem_registos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Guarda estado.
    '''</summary>
    Public Shared ReadOnly Property guarda_estado() As String
        Get
            Return ResourceManager.GetString("guarda_estado", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O idioma com código {0} já está definido para este tipo de documento..
    '''</summary>
    Public Shared ReadOnly Property idioma_existente() As String
        Get
            Return ResourceManager.GetString("idioma_existente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A Regiao {0} já está definida para este iva..
    '''</summary>
    Public Shared ReadOnly Property iva_regiao_existente() As String
        Get
            Return ResourceManager.GetString("iva_regiao_existente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AUTENTICAÇÃO.
    '''</summary>
    Public Shared ReadOnly Property janelaAutenticacao() As String
        Get
            Return ResourceManager.GetString("janelaAutenticacao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Atenção! Existem alterações pendentes. Pretende continuar e gravar as mesmas?.
    '''</summary>
    Public Shared ReadOnly Property msg_opcoes_gravar_continuar() As String
        Get
            Return ResourceManager.GetString("msg_opcoes_gravar_continuar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Não.
    '''</summary>
    Public Shared ReadOnly Property nao() As String
        Get
            Return ResourceManager.GetString("nao", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Não existem ficheiros selecionados/arrastados....
    '''</summary>
    Public Shared ReadOnly Property nao_existem_anexos() As String
        Get
            Return ResourceManager.GetString("nao_existem_anexos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adicionado com sucesso..
    '''</summary>
    Public Shared ReadOnly Property notificacao_grelha_add() As String
        Get
            Return ResourceManager.GetString("notificacao_grelha_add", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Atualizado com sucesso..
    '''</summary>
    Public Shared ReadOnly Property notificacao_grelha_rav() As String
        Get
            Return ResourceManager.GetString("notificacao_grelha_rav", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Removido com sucesso..
    '''</summary>
    Public Shared ReadOnly Property notificacao_grelha_rem() As String
        Get
            Return ResourceManager.GetString("notificacao_grelha_rem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Problemas.
    '''</summary>
    Public Shared ReadOnly Property problemas_encontrados() As String
        Get
            Return ResourceManager.GetString("problemas_encontrados", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantidade Total.
    '''</summary>
    Public Shared ReadOnly Property QuantidadeTotal() As String
        Get
            Return ResourceManager.GetString("QuantidadeTotal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remover esta linha?.
    '''</summary>
    Public Shared ReadOnly Property Remover_Linha() As String
        Get
            Return ResourceManager.GetString("Remover_Linha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem a certeza que deseja remover esta linha?.
    '''</summary>
    Public Shared ReadOnly Property removerLinha() As String
        Get
            Return ResourceManager.GetString("removerLinha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Resultados da Pesquisa.
    '''</summary>
    Public Shared ReadOnly Property resultado_pesquisa() As String
        Get
            Return ResourceManager.GetString("resultado_pesquisa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Selecionar uma listagem.
    '''</summary>
    Public Shared ReadOnly Property selecionar_listagem() As String
        Get
            Return ResourceManager.GetString("selecionar_listagem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Selecionar as linhas todas.
    '''</summary>
    Public Shared ReadOnly Property SelecionarLinhasTodas() As String
        Get
            Return ResourceManager.GetString("SelecionarLinhasTodas", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Selecionar.
    '''</summary>
    Public Shared ReadOnly Property selecione_um_item() As String
        Get
            Return ResourceManager.GetString("selecione_um_item", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sem empresa.
    '''</summary>
    Public Shared ReadOnly Property sem_empresa() As String
        Get
            Return ResourceManager.GetString("sem_empresa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A série com código {0} já está definida para este tipo de documento..
    '''</summary>
    Public Shared ReadOnly Property serie_existente() As String
        Get
            Return ResourceManager.GetString("serie_existente", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sim.
    '''</summary>
    Public Shared ReadOnly Property sim() As String
        Get
            Return ResourceManager.GetString("sim", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clique para colapsar barra para a Direita.
    '''</summary>
    Public Shared ReadOnly Property splitter_colapsar_direita() As String
        Get
            Return ResourceManager.GetString("splitter_colapsar_direita", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clique para colapsar barra para a Esquerda.
    '''</summary>
    Public Shared ReadOnly Property splitter_colapsar_esquerda() As String
        Get
            Return ResourceManager.GetString("splitter_colapsar_esquerda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem que selecionar pelo menos 1 linha!.
    '''</summary>
    Public Shared ReadOnly Property tem_que_selecionar_uma_linha() As String
        Get
            Return ResourceManager.GetString("tem_que_selecionar_uma_linha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tem que ter no mínimo, uma linha com quantidade diferente de 0!.
    '''</summary>
    Public Shared ReadOnly Property tem_que_ter_quantidade() As String
        Get
            Return ResourceManager.GetString("tem_que_ter_quantidade", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tempo Total.
    '''</summary>
    Public Shared ReadOnly Property TempoTotal() As String
        Get
            Return ResourceManager.GetString("TempoTotal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Todos.
    '''</summary>
    Public Shared ReadOnly Property todos() As String
        Get
            Return ResourceManager.GetString("todos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O nº contribuinte indicado é inválido..
    '''</summary>
    Public Shared ReadOnly Property ValidaNIF() As String
        Get
            Return ResourceManager.GetString("ValidaNIF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O código da série do tipo de documento deve ser alfanumérico..
    '''</summary>
    Public Shared ReadOnly Property ValidaSerie() As String
        Get
            Return ResourceManager.GetString("ValidaSerie", resourceCulture)
        End Get
    End Property
End Class
