'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class EstruturaDeErros
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OticasTraducao.EstruturaDeErros", GetType(EstruturaDeErros).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O concelho está associado a um ou mais códigos postais..
    '''</summary>
    Public Shared ReadOnly Property FK_tbCodigosPostais_IdConcelho() As String
        Get
            Return ResourceManager.GetString("FK_tbCodigosPostais_IdConcelho", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O concelho está associado a um ou mais códigos postais..
    '''</summary>
    Public Shared ReadOnly Property FK_tbCodigosPostais_IdConcelho_deleted() As String
        Get
            Return ResourceManager.GetString("FK_tbCodigosPostais_IdConcelho_deleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O distrito está associado a um ou mais concelhos..
    '''</summary>
    Public Shared ReadOnly Property FK_tbConcelhos_IdDistrito() As String
        Get
            Return ResourceManager.GetString("FK_tbConcelhos_IdDistrito", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to O distrito está associado a um ou mais concelhos..
    '''</summary>
    Public Shared ReadOnly Property FK_tbConcelhos_IdDistrito_deleted() As String
        Get
            Return ResourceManager.GetString("FK_tbConcelhos_IdDistrito_deleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A sigla está associada a uma ou mais Moedas..
    '''</summary>
    Public Shared ReadOnly Property FK_tbMoedas_IDSistemaMoeda() As String
        Get
            Return ResourceManager.GetString("FK_tbMoedas_IDSistemaMoeda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A sigla está associada a uma ou mais Moedas..
    '''</summary>
    Public Shared ReadOnly Property FK_tbMoedas_IDSistemaMoeda_deleted() As String
        Get
            Return ResourceManager.GetString("FK_tbMoedas_IDSistemaMoeda_deleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A sigla está associada a um ou mais Paises.	.
    '''</summary>
    Public Shared ReadOnly Property FK_tbPaises_IdSigla() As String
        Get
            Return ResourceManager.GetString("FK_tbPaises_IdSigla", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A sigla está associada a um ou mais Paises..
    '''</summary>
    Public Shared ReadOnly Property FK_tbPaises_IdSigla_deleted() As String
        Get
            Return ResourceManager.GetString("FK_tbPaises_IdSigla_deleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A loja está associada a uma ou mais séries de numeração..
    '''</summary>
    Public Shared ReadOnly Property FK_tbSeriesNumeracao_IDLoja() As String
        Get
            Return ResourceManager.GetString("FK_tbSeriesNumeracao_IDLoja", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A loja está associada a uma ou mais séries de numeração..
    '''</summary>
    Public Shared ReadOnly Property FK_tbSeriesNumeracao_IDLoja_deleted() As String
        Get
            Return ResourceManager.GetString("FK_tbSeriesNumeracao_IDLoja_deleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um armazém com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbArmazens_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbArmazens_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma localização com este código associada a este ou outro armazém..
    '''</summary>
    Public Shared ReadOnly Property IX_tbArmazens_Localizacoes() As String
        Get
            Return ResourceManager.GetString("IX_tbArmazens_Localizacoes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um artigo com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbArtigos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbArtigos_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um artigo com este código de barras..
    '''</summary>
    Public Shared ReadOnly Property IX_tbArtigos_CodigoBarras() As String
        Get
            Return ResourceManager.GetString("IX_tbArtigos_CodigoBarras", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um cliente / outro devedor com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbClientes_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbClientes_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um código postal com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbCodigosPostais_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbCodigosPostais_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe o concelho com este código para o distrito indicado..
    '''</summary>
    Public Shared ReadOnly Property IX_tbConcelhos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbConcelhos_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma condição de pagamento com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbCondicoesPagamento_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbCondicoesPagamento_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um distrito com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbDistritos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbDistritos_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um grupo com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbEmpresas_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbEmpresas_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um estado com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbEstados_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbEstados_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma família com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbFamilias_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbFamilias_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma forma de expedição com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbFormasExpedicao_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbFormasExpedicao_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma forma de pagamento com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbFormasPagamento_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbFormasPagamento_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um fornecedor / outro credor com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbFornecedores_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbFornecedores_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um grupo com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbGrupos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbGrupos_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um idioma com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbIdiomas_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbIdiomas_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um imposto de selo com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbImpostoSelo_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbImpostoSelo_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma taxa de iva com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbIVA_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbIVA_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma Loja com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbLojas_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbLojas_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma marca com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbMarcas_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbMarcas_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma Moeda com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbMoedas_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbMoedas_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um país com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbPaises_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbPaises_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma profissão com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbProfissoes_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbProfissoes_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe uma Série com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbSeriesNumeracao_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbSeriesNumeracao_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um setor de atividade com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbSetoresAtividade_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbSetoresAtividade_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um tipo de artigo com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbTiposArtigos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbTiposArtigos_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um tipo de contato com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbTiposContatos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbTiposContatos_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe o tipo de documento com este código para o módulo / tipo indicado..
    '''</summary>
    Public Shared ReadOnly Property IX_tbTiposDocumento_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbTiposDocumento_Codigo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Já existe um tipo de fornecimento com este código..
    '''</summary>
    Public Shared ReadOnly Property IX_tbTiposFornecimentos_Codigo() As String
        Get
            Return ResourceManager.GetString("IX_tbTiposFornecimentos_Codigo", resourceCulture)
        End Get
    End Property
End Class
