'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosDimensoesEmpresa
    Public Property ID As Long
    Public Property IDArtigosDimensoes As Long

    Public Overridable Property tbArtigosDimensoes As tbArtigosDimensoes

End Class
