'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosDimensoes
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property IDDimensaoLinha1 As Nullable(Of Long)
    Public Property IDDimensaoLinha2 As Nullable(Of Long)
    Public Property CodigoBarras As String
    Public Property StkMin As Nullable(Of Double)
    Public Property StkMax As Nullable(Of Double)
    Public Property QtdPendenteCompras As Nullable(Of Double)
    Public Property UPC As Nullable(Of Double)
    Public Property UltimoCustoAdicional As Nullable(Of Double)
    Public Property CustoMedio As Nullable(Of Double)
    Public Property PV1 As Nullable(Of Double)
    Public Property PV2 As Nullable(Of Double)
    Public Property PV3 As Nullable(Of Double)
    Public Property PV4 As Nullable(Of Double)
    Public Property QtdStockEnc As Nullable(Of Double)
    Public Property PVP As Nullable(Of Double)
    Public Property TextoExtra As String
    Public Property PV5 As Nullable(Of Double)
    Public Property PV6 As Nullable(Of Double)
    Public Property PV7 As Nullable(Of Double)
    Public Property PV8 As Nullable(Of Double)
    Public Property PV9 As Nullable(Of Double)
    Public Property PV10 As Nullable(Of Double)
    Public Property CodEstatistico As String
    Public Property TextoExtra2 As String
    Public Property TextoExtra3 As String
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property StkArtigo As Nullable(Of Double)
    Public Property StkArmazem As Nullable(Of Double)
    Public Property StkEncomenda As Nullable(Of Double)
    Public Property Activo As Nullable(Of Boolean)
    Public Property CustoPadrao As Nullable(Of Double)
    Public Property IDTipoDocumentoUPC As Nullable(Of Long)
    Public Property IDDocumentoUPC As Nullable(Of Long)
    Public Property DataControloUPC As Nullable(Of Date)
    Public Property RecalculaUPC As Nullable(Of Boolean)
    Public Property StkArtigo2 As Nullable(Of Double)
    Public Property UltPrecoComp As Nullable(Of Double)
    Public Property QtdPendenteCompras2 As Nullable(Of Double)

    Public Overridable Property tbArtigos As tbArtigos
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbDimensoesLinhas As tbDimensoesLinhas
    Public Overridable Property tbDimensoesLinhas1 As tbDimensoesLinhas
    Public Overridable Property tbArtigosDimensoesEmpresa As ICollection(Of tbArtigosDimensoesEmpresa) = New HashSet(Of tbArtigosDimensoesEmpresa)
    Public Overridable Property tbCCStockArtigos As ICollection(Of tbCCStockArtigos) = New HashSet(Of tbCCStockArtigos)
    Public Overridable Property tbDocumentosComprasLinhasDimensoes As ICollection(Of tbDocumentosComprasLinhasDimensoes) = New HashSet(Of tbDocumentosComprasLinhasDimensoes)
    Public Overridable Property tbDocumentosStockLinhasDimensoes As ICollection(Of tbDocumentosStockLinhasDimensoes) = New HashSet(Of tbDocumentosStockLinhasDimensoes)
    Public Overridable Property tbDocumentosVendasLinhasDimensoes As ICollection(Of tbDocumentosVendasLinhasDimensoes) = New HashSet(Of tbDocumentosVendasLinhasDimensoes)
    Public Overridable Property tbStockArtigos As ICollection(Of tbStockArtigos) = New HashSet(Of tbStockArtigos)
    Public Overridable Property tbStockArtigosNecessidades As ICollection(Of tbStockArtigosNecessidades) = New HashSet(Of tbStockArtigosNecessidades)

End Class
