'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosComponentes
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property IDArtigoDimensaoLinha1 As Nullable(Of Long)
    Public Property IDArtigoDimensaoLinha2 As Nullable(Of Long)
    Public Property IDArtigoComponente As Long
    Public Property IDArtigoDimensaoLinha1Componente As Nullable(Of Long)
    Public Property IDArtigoDimensaoLinha2Componente As Nullable(Of Long)
    Public Property Quantidade As Nullable(Of Double)
    Public Property UltimoPrecoCusto As Nullable(Of Double)
    Public Property PrecoCustoMedio As Nullable(Of Double)
    Public Property PrecoCustoPadrao As Nullable(Of Double)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Long
    Public Property IDSistemaTiposComponente As Nullable(Of Long)

    Public Overridable Property tbArtigos As tbArtigos
    Public Overridable Property tbArtigos1 As tbArtigos
    Public Overridable Property tbDimensoesLinhas As tbDimensoesLinhas
    Public Overridable Property tbDimensoesLinhas1 As tbDimensoesLinhas
    Public Overridable Property tbDimensoesLinhas2 As tbDimensoesLinhas
    Public Overridable Property tbDimensoesLinhas3 As tbDimensoesLinhas
    Public Overridable Property tbSistemaTiposComponente As tbSistemaTiposComponente

End Class
