'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosPrecos
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property IDCodigoPreco As Long
    Public Property ValorComIva As Nullable(Of Double)
    Public Property ValorSemIva As Nullable(Of Double)
    Public Property UPCPercentagem As Nullable(Of Double)
    Public Property IDUnidade As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Long
    Public Property IDLoja As Nullable(Of Long)

    Public Overridable Property tbArtigos As tbArtigos
    Public Overridable Property tbArtigosPrecos1 As tbArtigosPrecos
    Public Overridable Property tbArtigosPrecos2 As tbArtigosPrecos
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbSistemaCodigosPrecos As tbSistemaCodigosPrecos
    Public Overridable Property tbUnidades As tbUnidades

End Class
