'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosLotes
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property DataFabrico As Nullable(Of Date)
    Public Property DataValidade As Nullable(Of Date)
    Public Property Sistema As Nullable(Of Boolean)
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Long

    Public Overridable Property tbArtigos As tbArtigos
    Public Overridable Property tbCCStockArtigos As ICollection(Of tbCCStockArtigos) = New HashSet(Of tbCCStockArtigos)
    Public Overridable Property tbDocumentosComprasLinhas As ICollection(Of tbDocumentosComprasLinhas) = New HashSet(Of tbDocumentosComprasLinhas)
    Public Overridable Property tbDocumentosStockContagemLinhas As ICollection(Of tbDocumentosStockContagemLinhas) = New HashSet(Of tbDocumentosStockContagemLinhas)
    Public Overridable Property tbDocumentosStockLinhas As ICollection(Of tbDocumentosStockLinhas) = New HashSet(Of tbDocumentosStockLinhas)
    Public Overridable Property tbDocumentosVendasLinhas As ICollection(Of tbDocumentosVendasLinhas) = New HashSet(Of tbDocumentosVendasLinhas)
    Public Overridable Property tbStockArtigos As ICollection(Of tbStockArtigos) = New HashSet(Of tbStockArtigos)
    Public Overridable Property tbStockArtigosNecessidades As ICollection(Of tbStockArtigosNecessidades) = New HashSet(Of tbStockArtigosNecessidades)

End Class
