'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArmazens
    Public Property ID As Long
    Public Property IDLoja As Nullable(Of Long)
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDCodigoPostal As Nullable(Of Long)
    Public Property IDConcelho As Nullable(Of Long)
    Public Property IDDistrito As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Morada As String
    Public Property IDPais As Nullable(Of Long)

    Public Overridable Property tbCodigosPostais As tbCodigosPostais
    Public Overridable Property tbConcelhos As tbConcelhos
    Public Overridable Property tbDistritos As tbDistritos
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbPaises As tbPaises
    Public Overridable Property tbArmazensLocalizacoes As ICollection(Of tbArmazensLocalizacoes) = New HashSet(Of tbArmazensLocalizacoes)
    Public Overridable Property tbArtigosArmazensLocalizacoes As ICollection(Of tbArtigosArmazensLocalizacoes) = New HashSet(Of tbArtigosArmazensLocalizacoes)
    Public Overridable Property tbCCStockArtigos As ICollection(Of tbCCStockArtigos) = New HashSet(Of tbCCStockArtigos)
    Public Overridable Property tbDocumentosComprasLinhas As ICollection(Of tbDocumentosComprasLinhas) = New HashSet(Of tbDocumentosComprasLinhas)
    Public Overridable Property tbDocumentosComprasLinhas1 As ICollection(Of tbDocumentosComprasLinhas) = New HashSet(Of tbDocumentosComprasLinhas)
    Public Overridable Property tbDocumentosStockContagem As ICollection(Of tbDocumentosStockContagem) = New HashSet(Of tbDocumentosStockContagem)
    Public Overridable Property tbDocumentosStockLinhas As ICollection(Of tbDocumentosStockLinhas) = New HashSet(Of tbDocumentosStockLinhas)
    Public Overridable Property tbDocumentosStockLinhas1 As ICollection(Of tbDocumentosStockLinhas) = New HashSet(Of tbDocumentosStockLinhas)
    Public Overridable Property tbDocumentosVendasLinhas As ICollection(Of tbDocumentosVendasLinhas) = New HashSet(Of tbDocumentosVendasLinhas)
    Public Overridable Property tbDocumentosVendasLinhas1 As ICollection(Of tbDocumentosVendasLinhas) = New HashSet(Of tbDocumentosVendasLinhas)
    Public Overridable Property tbStockArtigos As ICollection(Of tbStockArtigos) = New HashSet(Of tbStockArtigos)
    Public Overridable Property tbStockArtigosNecessidades As ICollection(Of tbStockArtigosNecessidades) = New HashSet(Of tbStockArtigosNecessidades)

End Class
