'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosArmazensLocalizacoes
    Public Property ID As Long
    Public Property IDArtigo As Nullable(Of Long)
    Public Property IDArmazem As Long
    Public Property PorDefeito As Nullable(Of Boolean)
    Public Property Sistema As Nullable(Of Boolean)
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Long
    Public Property Ativo As Boolean
    Public Property IDArmazemLocalizacao As Nullable(Of Long)

    Public Overridable Property tbArmazens As tbArmazens
    Public Overridable Property tbArmazensLocalizacoes As tbArmazensLocalizacoes
    Public Overridable Property tbArtigos As tbArtigos

End Class
