'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosStock
    Public Property ID As Long
    Public Property PrimeiraEntrada As Nullable(Of Date)
    Public Property UltimaEntrada As Nullable(Of Date)
    Public Property PrimeiraSaida As Nullable(Of Date)
    Public Property UltimaSaida As Nullable(Of Date)
    Public Property Atual As Nullable(Of Double)
    Public Property Reservado As Nullable(Of Double)
    Public Property Sistema As Nullable(Of Boolean)
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property StockAtual2 As Nullable(Of Double)
    Public Property IDArtigo As Nullable(Of Long)
    Public Property Reservado2 As Nullable(Of Double)
    Public Property StockReqPendente As Nullable(Of Double)
    Public Property StockReqPendente2Uni As Nullable(Of Double)

    Public Overridable Property tbArtigos As tbArtigos

End Class
