'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosDadosFinanceirosPVsUPCPerc
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property PV1 As Nullable(Of Double)
    Public Property PV2 As Nullable(Of Double)
    Public Property PV3 As Nullable(Of Double)
    Public Property PV4 As Nullable(Of Double)
    Public Property PV5 As Nullable(Of Double)
    Public Property PV6 As Nullable(Of Double)
    Public Property PV7 As Nullable(Of Double)
    Public Property PV8 As Nullable(Of Double)
    Public Property PV9 As Nullable(Of Double)
    Public Property PV10 As Nullable(Of Double)
    Public Property PV1IVA As Nullable(Of Double)
    Public Property PV2IVA As Nullable(Of Double)
    Public Property PV3IVA As Nullable(Of Double)
    Public Property PV4IVA As Nullable(Of Double)
    Public Property PV5IVA As Nullable(Of Double)
    Public Property PV6IVA As Nullable(Of Double)
    Public Property PV7IVA As Nullable(Of Double)
    Public Property PV8IVA As Nullable(Of Double)
    Public Property PV9IVA As Nullable(Of Double)
    Public Property PV10IVA As Nullable(Of Double)
    Public Property PercUPC1 As Nullable(Of Double)
    Public Property PercUPC2 As Nullable(Of Double)
    Public Property PercUPC3 As Nullable(Of Double)
    Public Property PercUPC4 As Nullable(Of Double)
    Public Property PercUPC5 As Nullable(Of Double)
    Public Property PercUPC6 As Nullable(Of Double)
    Public Property PercUPC7 As Nullable(Of Double)
    Public Property PercUPC8 As Nullable(Of Double)
    Public Property PercUPC9 As Nullable(Of Double)
    Public Property PercUPC10 As Nullable(Of Double)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArtigos As tbArtigos

End Class
