'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbArtigosDadosFinanceiros
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property IDIva As Long
    Public Property PercentagemDedutivel As Nullable(Of Double)
    Public Property PercentagemIncidencia As Nullable(Of Double)
    Public Property TextoMotivoIsencaoPersonalizado As String
    Public Property SujeitoProRata As Boolean
    Public Property IDArtigoImpostoSelo As Nullable(Of Long)
    Public Property UltimoPrecoCusto As Nullable(Of Double)
    Public Property CustoMedio As Nullable(Of Double)
    Public Property PrecoPadrao As Nullable(Of Double)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArtigos As tbArtigos

End Class
