'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbATEstadoComunicacaoLinhas
    Public Property ID As Long
    Public Property IDATEstadoComunicacao As Long
    Public Property ReturnCode As Nullable(Of Long)
    Public Property ReturnMessage As String
    Public Property ATDocCodeID As String
    Public Property UtilizadorAlteracao As String
    Public Property DataHoraPedido As Nullable(Of Date)
    Public Property Acao As String
    Public Property XMLResposta As String
    Public Property XMLPedidoAT As String
    Public Property XMLRespostaAT As String

    Public Overridable Property tbATEstadoComunicacao As tbATEstadoComunicacao

End Class
