'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbATEstadoComunicacao
    Public Property ID As Long
    Public Property IDDocumento As Nullable(Of Long)
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property TipoDocumento As String
    Public Property IDSerie As Nullable(Of Long)
    Public Property Serie As String
    Public Property Ano As Nullable(Of Long)
    Public Property Numero As Nullable(Of Long)
    Public Property DataDocumento As Nullable(Of Date)
    Public Property TipoEntidade As Nullable(Of Long)
    Public Property CodigoEntidade As String
    Public Property NomeEntidade As String
    Public Property ReturnCode As Nullable(Of Long)
    Public Property ReturnMessage As String
    Public Property ATDocCodeID As String
    Public Property UtilizadorCriacao As String
    Public Property DataHoraPedido As Nullable(Of Date)
    Public Property TipoDocumentoDescricao As String
    Public Property Selecionado As Nullable(Of Boolean)
    Public Property IDLoja As Nullable(Of Long)
    Public Property CodigoLoja As String
    Public Property NomeLoja As String
    Public Property Acao As String
    Public Property XMLResposta As String
    Public Property DataHoraCarga As Nullable(Of Date)
    Public Property Manual As Boolean
    Public Property XMLPedidoAT As String
    Public Property XMLRespostaAT As String
    Public Property strTabela As String

    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbTiposDocumentoSeries As tbTiposDocumentoSeries
    Public Overridable Property tbATEstadoComunicacaoLinhas As ICollection(Of tbATEstadoComunicacaoLinhas) = New HashSet(Of tbATEstadoComunicacaoLinhas)

End Class
