'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbCCEntidades
    Public Property ID As Long
    Public Property Natureza As String
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDTipoEntidade As Nullable(Of Long)
    Public Property IDEntidade As Nullable(Of Long)
    Public Property NomeFiscal As String
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDTipoDocumentoSeries As Nullable(Of Long)
    Public Property IDDocumento As Nullable(Of Long)
    Public Property NumeroDocumento As String
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Descricao As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TotalMoeda As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

End Class
