'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbCCStockArtigos
    Public Property ID As Long
    Public Property IDArtigo As Long
    Public Property Descricao As String
    Public Property Natureza As String
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDArmazem As Nullable(Of Long)
    Public Property IDArmazemLocalizacao As Nullable(Of Long)
    Public Property IDArtigoLote As Nullable(Of Long)
    Public Property IDArtigoNumeroSerie As Nullable(Of Long)
    Public Property IDArtigoDimensao As Nullable(Of Long)
    Public Property IDMoeda As Nullable(Of Long)
    Public Property IDTipoEntidade As Nullable(Of Long)
    Public Property IDEntidade As Nullable(Of Long)
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDDocumento As Nullable(Of Long)
    Public Property IDLinhaDocumento As Nullable(Of Long)
    Public Property NumeroDocumento As String
    Public Property IDTipoDocumentoOrigem As Nullable(Of Long)
    Public Property IDDocumentoOrigem As Nullable(Of Long)
    Public Property IDLinhaDocumentoOrigem As Nullable(Of Long)
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Quantidade As Nullable(Of Double)
    Public Property QuantidadeStock As Nullable(Of Double)
    Public Property QuantidadeStock2 As Nullable(Of Double)
    Public Property QtdStockAnterior As Nullable(Of Double)
    Public Property QtdStockAtual As Nullable(Of Double)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property PrecoUnitario As Nullable(Of Double)
    Public Property PrecoUnitarioEfetivo As Nullable(Of Double)
    Public Property PrecoUnitarioMoedaRef As Nullable(Of Double)
    Public Property PrecoUnitarioEfetivoMoedaRef As Nullable(Of Double)
    Public Property UPCMoedaRef As Nullable(Of Double)
    Public Property PCMAnteriorMoedaRef As Nullable(Of Double)
    Public Property PCMAtualMoedaRef As Nullable(Of Double)
    Public Property PVMoedaRef As Nullable(Of Double)
    Public Property Recalcular As Nullable(Of Boolean)
    Public Property QtdAfetacaoStock As Nullable(Of Double)
    Public Property QtdAfetacaoStock2 As Nullable(Of Double)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property UPCompraMoedaRef As Nullable(Of Double)
    Public Property UltCustosAdicionaisMoedaRef As Nullable(Of Double)
    Public Property UltDescComerciaisMoedaRef As Nullable(Of Double)
    Public Property DataControloInterno As Nullable(Of Date)
    Public Property IDTiposDocumentoSeries As Nullable(Of Long)
    Public Property IDTiposDocumentoSeriesOrigem As Nullable(Of Long)
    Public Property VossoNumeroDocumento As String
    Public Property VossoNumeroDocumentoOrigem As String
    Public Property NumeroDocumentoOrigem As Nullable(Of Long)
    Public Property IDArtigoPara As Nullable(Of Long)
    Public Property IDArtigoPA As Nullable(Of Long)
    Public Property IDTipoDocumentoOrigemInicial As Nullable(Of Long)
    Public Property IDDocumentoOrigemInicial As Nullable(Of Long)
    Public Property IDLinhaDocumentoOrigemInicial As Nullable(Of Long)
    Public Property DocumentoOrigemInicial As String
    Public Property QtdStockReserva As Nullable(Of Double)
    Public Property QtdStockReserva2Uni As Nullable(Of Double)

    Public Overridable Property tbArmazens As tbArmazens
    Public Overridable Property tbArmazensLocalizacoes As tbArmazensLocalizacoes
    Public Overridable Property tbArtigos As tbArtigos
    Public Overridable Property tbArtigos1 As tbArtigos
    Public Overridable Property tbArtigos2 As tbArtigos
    Public Overridable Property tbArtigosDimensoes As tbArtigosDimensoes
    Public Overridable Property tbArtigosLotes As tbArtigosLotes
    Public Overridable Property tbArtigosNumerosSeries As tbArtigosNumerosSeries
    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbTiposDocumento1 As tbTiposDocumento
    Public Overridable Property tbSistemaTiposEntidade As tbSistemaTiposEntidade
    Public Overridable Property tbTiposDocumento2 As tbTiposDocumento
    Public Overridable Property tbTiposDocumentoSeries As tbTiposDocumentoSeries
    Public Overridable Property tbTiposDocumentoSeries1 As tbTiposDocumentoSeries

End Class
