'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbClientesLojas
    Public Property ID As Long
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDCliente As Long
    Public Property TotalVendas As Double
    Public Property Saldo As Double
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Nullable(Of Integer)

    Public Overridable Property tbClientes As tbClientes
    Public Overridable Property tbLojas As tbLojas

End Class
