'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbClientesMoradas
    Public Property ID As Long
    Public Property Descricao As String
    Public Property Rota As String
    Public Property IDCliente As Long
    Public Property IDCodigoPostal As Nullable(Of Long)
    Public Property IDConcelho As Nullable(Of Long)
    Public Property IDDistrito As Nullable(Of Long)
    Public Property IDPais As Nullable(Of Long)
    Public Property GPS As String
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property OrdemMorada As Integer
    Public Property Ordem As Integer
    Public Property Morada As String
    Public Property Esquecido As Nullable(Of Boolean)

    Public Overridable Property tbClientes As tbClientes
    Public Overridable Property tbCodigosPostais As tbCodigosPostais
    Public Overridable Property tbConcelhos As tbConcelhos
    Public Overridable Property tbDistritos As tbDistritos
    Public Overridable Property tbPaises As tbPaises

End Class
