'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbConcelhos
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDDistrito As Long
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArmazens As ICollection(Of tbArmazens) = New HashSet(Of tbArmazens)
    Public Overridable Property tbBancosMoradas As ICollection(Of tbBancosMoradas) = New HashSet(Of tbBancosMoradas)
    Public Overridable Property tbClientesMoradas As ICollection(Of tbClientesMoradas) = New HashSet(Of tbClientesMoradas)
    Public Overridable Property tbCodigosPostais As ICollection(Of tbCodigosPostais) = New HashSet(Of tbCodigosPostais)
    Public Overridable Property tbDistritos As tbDistritos
    Public Overridable Property tbContasBancariasMoradas As ICollection(Of tbContasBancariasMoradas) = New HashSet(Of tbContasBancariasMoradas)
    Public Overridable Property tbDocumentosCompras As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosCompras1 As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosCompras2 As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosCompras3 As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosStock As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStock1 As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStock2 As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStock3 As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosVendas As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendas1 As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendas2 As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendas3 As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbEntidadesMoradas As ICollection(Of tbEntidadesMoradas) = New HashSet(Of tbEntidadesMoradas)
    Public Overridable Property tbFornecedoresMoradas As ICollection(Of tbFornecedoresMoradas) = New HashSet(Of tbFornecedoresMoradas)
    Public Overridable Property tbMedicosTecnicosMoradas As ICollection(Of tbMedicosTecnicosMoradas) = New HashSet(Of tbMedicosTecnicosMoradas)
    Public Overridable Property tbPagamentosCompras As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbPagamentosCompras1 As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbPagamentosCompras2 As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbPagamentosCompras3 As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbRecibos As ICollection(Of tbRecibos) = New HashSet(Of tbRecibos)
    Public Overridable Property tbRecibosLinhas As ICollection(Of tbRecibosLinhas) = New HashSet(Of tbRecibosLinhas)

End Class
