'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbComunicacaoSmsTemplatesValores
    Public Property ID As Long
    Public Property IDComunicacaoSmsTemplatesRegras As Long
    Public Property IDSistemaComunicacaoSmsTemplatesValores As Long
    Public Property Ordem As Long
    Public Property Valor As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbComunicacaoSmsTemplatesRegras As tbComunicacaoSmsTemplatesRegras
    Public Overridable Property tbSistemaComunicacaoSmsTemplatesValores As tbSistemaComunicacaoSmsTemplatesValores

End Class
