'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbContasBancarias
    Public Property ID As Long
    Public Property IDLoja As Nullable(Of Long)
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDBanco As Long
    Public Property IDMoeda As Long
    Public Property Plafond As Nullable(Of Double)
    Public Property TaxaPlafond As Nullable(Of Double)
    Public Property PaisIban As String
    Public Property NIB As String
    Public Property SepaPrv As String
    Public Property VariavelContabilidade As String
    Public Property ContaCaixa As Boolean
    Public Property SaldoTotal As Nullable(Of Double)
    Public Property SaldoReconciliado As Nullable(Of Double)
    Public Property Observacoes As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbBancos As tbBancos
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbContasBancariasContatos As ICollection(Of tbContasBancariasContatos) = New HashSet(Of tbContasBancariasContatos)
    Public Overridable Property tbContasBancariasMoradas As ICollection(Of tbContasBancariasMoradas) = New HashSet(Of tbContasBancariasMoradas)

End Class
