'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbConsentimentos
    Public Property ID As Long
    Public Property IDCodigoEntidade As String
    Public Property CodigoEntidade As String
    Public Property DescricaoEntidade As String
    Public Property IDParametrizacaoConsentimentos As Long
    Public Property ComAssinatura As Boolean
    Public Property DataConsentimento As Date
    Public Property Titulo As String
    Public Property TituloSemFormatacao As String
    Public Property Cabecalho As String
    Public Property CabecalhoSemFormatacao As String
    Public Property Rodape As String
    Public Property RodapeSemFormatacao As String
    Public Property Ficheiro As String
    Public Property Caminho As String
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbParametrizacaoConsentimentos As tbParametrizacaoConsentimentos
    Public Overridable Property tbRespostasConsentimentos As ICollection(Of tbRespostasConsentimentos) = New HashSet(Of tbRespostasConsentimentos)

End Class
