'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbContabilidadeExportacao
    Public Property ID As Long
    Public Property Ordem As Long
    Public Property IDDocumento As Long
    Public Property Documento As String
    Public Property DataDocumento As Date
    Public Property IDLoja As Long
    Public Property CodigoLoja As String
    Public Property IDTiposDocumento As Long
    Public Property CodigoTipoDocumento As String
    Public Property IDTiposDocumentoSeries As Long
    Public Property CodigoTiposDocumentoSeries As String
    Public Property IDEntidade As Nullable(Of Long)
    Public Property CodigoEntidade As String
    Public Property Entidade As String
    Public Property IDTipoEntidade As Long
    Public Property CodigoTipoEntidade As String
    Public Property Diario As String
    Public Property CodDocumento As String
    Public Property RefleteClasseIVAContaFinanceira As Nullable(Of Boolean)
    Public Property ContaClasseIVA As String
    Public Property RefleteCentroCustoContaFinanceira As Nullable(Of Boolean)
    Public Property ContaCentroCusto As String
    Public Property Conta As String
    Public Property Valor As Nullable(Of Double)
    Public Property Natureza As String
    Public Property Gerado As Nullable(Of Boolean)
    Public Property Exportado As Nullable(Of Boolean)
    Public Property Erro As Nullable(Of Boolean)
    Public Property ListaErros As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property CodigoModulo As String
    Public Property NumeroDocumento As Nullable(Of Long)
    Public Property CodigoAlternativa As String
    Public Property DescricaoAlternativa As String
    Public Property CodigoDocumento As String
    Public Property ContaOrigem As String
    Public Property VossoNumeroDocumento As String
    Public Property DescricaoModulo As String
    Public Property CentroCusto As Nullable(Of Boolean)

End Class
