'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbComunicacaoSmsTemplatesGrupos
    Public Property ID As Long
    Public Property IDComunicacaoSmsTemplates As Long
    Public Property Ordem As Nullable(Of Long)
    Public Property MainCondition As String
    Public Property IDComunicacaoSmsTemplatesGrupos As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbComunicacaoSmsTemplates As tbComunicacaoSmsTemplates
    Public Overridable Property tbComunicacaoSmsTemplatesGrupos1 As ICollection(Of tbComunicacaoSmsTemplatesGrupos) = New HashSet(Of tbComunicacaoSmsTemplatesGrupos)
    Public Overridable Property tbComunicacaoSmsTemplatesGrupos2 As tbComunicacaoSmsTemplatesGrupos
    Public Overridable Property tbComunicacaoSmsTemplatesRegras As ICollection(Of tbComunicacaoSmsTemplatesRegras) = New HashSet(Of tbComunicacaoSmsTemplatesRegras)

End Class
