'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbControloValidacaoStock
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDDocumento As Nullable(Of Long)
    Public Property IDArtigo As Nullable(Of Long)
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDArmazem As Nullable(Of Long)
    Public Property IDArmazemLocalizacao As Nullable(Of Long)
    Public Property IDArtigoLote As Nullable(Of Long)
    Public Property IDArtigoNumeroSerie As Nullable(Of Long)
    Public Property IDArtigoDimensao As Nullable(Of Long)
    Public Property CodArtigo As String
    Public Property CodigoDimensao1 As String
    Public Property CodigoDimensao2 As String
    Public Property LimiteMax As Boolean
    Public Property LimiteMaxMsgBlq As Boolean
    Public Property LimiteMin As Boolean
    Public Property LimiteMinMsgBlq As Boolean
    Public Property RuturaUnd1 As Boolean
    Public Property RuturaUnd1MsgBlq As Boolean
    Public Property RuturaUnd2 As Boolean
    Public Property RuturaUnd2MsgBlq As Boolean
    Public Property UltEmLimiteMax As Nullable(Of Double)
    Public Property UltEmLimiteMin As Nullable(Of Double)
    Public Property UltEmRuturaUnd1 As Nullable(Of Double)
    Public Property UltEmRuturaUnd2 As Nullable(Of Double)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

End Class
