'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbDocumentosStockContagem
    Public Property ID As Long
    Public Property Documento As String
    Public Property NumeroDocumento As Long
    Public Property DataDocumento As Date
    Public Property IDTipoDocumento As Long
    Public Property IDArmazem As Nullable(Of Long)
    Public Property IDEstado As Long
    Public Property IDMoeda As Nullable(Of Long)
    Public Property IDTiposDocumentoSeries As Nullable(Of Long)
    Public Property NumeroInterno As Nullable(Of Long)
    Public Property IDLocalizacao As Nullable(Of Long)
    Public Property Filtro As String
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property Observacoes As String
    Public Property FaltamContar As Nullable(Of Double)
    Public Property Contados As Nullable(Of Double)
    Public Property Diferencas As Nullable(Of Double)
    Public Property IDLoja As Nullable(Of Long)
    Public Property DataControloInterno As Nullable(Of Date)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArmazens As tbArmazens
    Public Overridable Property tbArmazensLocalizacoes As tbArmazensLocalizacoes
    Public Overridable Property tbEstados As tbEstados
    Public Overridable Property tbSistemaMoedas As tbSistemaMoedas
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbTiposDocumentoSeries As tbTiposDocumentoSeries
    Public Overridable Property tbDocumentosStockContagemAnexos As ICollection(Of tbDocumentosStockContagemAnexos) = New HashSet(Of tbDocumentosStockContagemAnexos)
    Public Overridable Property tbDocumentosStockContagemLinhas As ICollection(Of tbDocumentosStockContagemLinhas) = New HashSet(Of tbDocumentosStockContagemLinhas)

End Class
