'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbDocumentosStock
    Public Property ID As Long
    Public Property IDTipoDocumento As Long
    Public Property NumeroDocumento As Nullable(Of Long)
    Public Property DataDocumento As Date
    Public Property Observacoes As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property TotalMoedaDocumento As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property LocalCarga As String
    Public Property DataCarga As Nullable(Of Date)
    Public Property HoraCarga As Nullable(Of Date)
    Public Property MoradaCarga As String
    Public Property IDCodigoPostalCarga As Nullable(Of Long)
    Public Property IDConcelhoCarga As Nullable(Of Long)
    Public Property IDDistritoCarga As Nullable(Of Long)
    Public Property LocalDescarga As String
    Public Property DataDescarga As Nullable(Of Date)
    Public Property HoraDescarga As Nullable(Of Date)
    Public Property MoradaDescarga As String
    Public Property IDCodigoPostalDescarga As Nullable(Of Long)
    Public Property IDConcelhoDescarga As Nullable(Of Long)
    Public Property IDDistritoDescarga As Nullable(Of Long)
    Public Property NomeDestinatario As String
    Public Property MoradaDestinatario As String
    Public Property IDCodigoPostalDestinatario As Nullable(Of Long)
    Public Property IDConcelhoDestinatario As Nullable(Of Long)
    Public Property IDDistritoDestinatario As Nullable(Of Long)
    Public Property SerieDocManual As String
    Public Property NumeroDocManual As String
    Public Property NumeroLinhas As Nullable(Of Long)
    Public Property Posto As String
    Public Property IDEstado As Nullable(Of Long)
    Public Property UtilizadorEstado As String
    Public Property DataHoraEstado As Nullable(Of Date)
    Public Property Assinatura As String
    Public Property VersaoChavePrivada As Nullable(Of Integer)
    Public Property NomeFiscal As String
    Public Property MoradaFiscal As String
    Public Property IDCodigoPostalFiscal As Nullable(Of Long)
    Public Property IDConcelhoFiscal As Nullable(Of Long)
    Public Property IDDistritoFiscal As Nullable(Of Long)
    Public Property ContribuinteFiscal As String
    Public Property SiglaPaisFiscal As String
    Public Property IDLoja As Nullable(Of Long)
    Public Property Impresso As Boolean
    Public Property ValorImposto As Nullable(Of Double)
    Public Property PercentagemDesconto As Nullable(Of Double)
    Public Property ValorDesconto As Nullable(Of Double)
    Public Property ValorPortes As Nullable(Of Double)
    Public Property IDTaxaIvaPortes As Nullable(Of Long)
    Public Property TaxaIvaPortes As Nullable(Of Double)
    Public Property MotivoIsencaoIva As String
    Public Property MotivoIsencaoPortes As String
    Public Property IDEspacoFiscalPortes As Nullable(Of Long)
    Public Property EspacoFiscalPortes As String
    Public Property IDRegimeIvaPortes As Nullable(Of Long)
    Public Property RegimeIvaPortes As String
    Public Property CustosAdicionais As Nullable(Of Double)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDFormaExpedicao As Nullable(Of Long)
    Public Property IDTiposDocumentoSeries As Long
    Public Property NumeroInterno As Nullable(Of Long)
    Public Property IDEntidade As Nullable(Of Long)
    Public Property IDTipoEntidade As Nullable(Of Long)
    Public Property IDCondicaoPagamento As Nullable(Of Long)
    Public Property IDLocalOperacao As Nullable(Of Long)
    Public Property CodigoAT As String
    Public Property IDPaisCarga As Nullable(Of Long)
    Public Property IDPaisDescarga As Nullable(Of Long)
    Public Property Matricula As String
    Public Property IDPaisFiscal As Nullable(Of Long)
    Public Property CodigoPostalFiscal As String
    Public Property DescricaoCodigoPostalFiscal As String
    Public Property DescricaoConcelhoFiscal As String
    Public Property DescricaoDistritoFiscal As String
    Public Property IDEspacoFiscal As Nullable(Of Long)
    Public Property IDRegimeIva As Nullable(Of Long)
    Public Property CodigoATInterno As String
    Public Property TipoFiscal As String
    Public Property Documento As String
    Public Property CodigoTipoEstado As String
    Public Property CodigoDocOrigem As String
    Public Property DistritoCarga As String
    Public Property ConcelhoCarga As String
    Public Property CodigoPostalCarga As String
    Public Property SiglaPaisCarga As String
    Public Property DistritoDescarga As String
    Public Property ConcelhoDescarga As String
    Public Property CodigoPostalDescarga As String
    Public Property SiglaPaisDescarga As String
    Public Property CodigoEntidade As String
    Public Property CodigoMoeda As String
    Public Property MensagemDocAT As String
    Public Property IDSisTiposDocPU As Nullable(Of Long)
    Public Property CodigoSisTiposDocPU As String
    Public Property DocManual As Nullable(Of Boolean)
    Public Property DocReposicao As Nullable(Of Boolean)
    Public Property DataAssinatura As Nullable(Of Date)
    Public Property DataControloInterno As Nullable(Of Date)
    Public Property SubTotal As Nullable(Of Double)
    Public Property DescontosLinha As Nullable(Of Double)
    Public Property TotalIVA As Nullable(Of Double)
    Public Property DataVencimento As Nullable(Of Date)
    Public Property VossoNumeroDocumento As String
    Public Property Satisfeito As Nullable(Of Boolean)
    Public Property SegundaVia As Nullable(Of Boolean)
    Public Property DataUltimaImpressao As Nullable(Of Date)
    Public Property NumeroImpressoes As Nullable(Of Integer)
    Public Property IDLojaUltimaImpressao As Nullable(Of Long)
    Public Property IDDocReserva As Nullable(Of Long)
    Public Property DataEntrega As Nullable(Of Date)
    Public Property RazaoEstado As String
    Public Property IDLojaSede As Nullable(Of Long)
    Public Property MoradaSede As String
    Public Property CodigoPostalSede As String
    Public Property LocalidadeSede As String
    Public Property TelefoneSede As String
    Public Property ATCUD As String
    Public Property ATQRCode As Byte()
    Public Property ATQRCodeTexto As String

    Public Overridable Property tbClientes As tbClientes
    Public Overridable Property tbCodigosPostais As tbCodigosPostais
    Public Overridable Property tbCodigosPostais1 As tbCodigosPostais
    Public Overridable Property tbCodigosPostais2 As tbCodigosPostais
    Public Overridable Property tbCodigosPostais3 As tbCodigosPostais
    Public Overridable Property tbConcelhos As tbConcelhos
    Public Overridable Property tbConcelhos1 As tbConcelhos
    Public Overridable Property tbConcelhos2 As tbConcelhos
    Public Overridable Property tbConcelhos3 As tbConcelhos
    Public Overridable Property tbCondicoesPagamento As tbCondicoesPagamento
    Public Overridable Property tbDistritos As tbDistritos
    Public Overridable Property tbDistritos1 As tbDistritos
    Public Overridable Property tbDistritos2 As tbDistritos
    Public Overridable Property tbDistritos3 As tbDistritos
    Public Overridable Property tbDocumentosCompras As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosStock1 As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStock2 As tbDocumentosStock
    Public Overridable Property tbEstados As tbEstados
    Public Overridable Property tbFormasExpedicao As tbFormasExpedicao
    Public Overridable Property tbIVA As tbIVA
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbLojas1 As tbLojas
    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbPaises As tbPaises
    Public Overridable Property tbPaises1 As tbPaises
    Public Overridable Property tbPaises2 As tbPaises
    Public Overridable Property tbSistemaEspacoFiscal As tbSistemaEspacoFiscal
    Public Overridable Property tbSistemaEspacoFiscal1 As tbSistemaEspacoFiscal
    Public Overridable Property tbSistemaRegimeIVA As tbSistemaRegimeIVA
    Public Overridable Property tbSistemaRegimeIVA1 As tbSistemaRegimeIVA
    Public Overridable Property tbSistemaRegioesIVA As tbSistemaRegioesIVA
    Public Overridable Property tbSistemaTiposDocumentoPrecoUnitario As tbSistemaTiposDocumentoPrecoUnitario
    Public Overridable Property tbSistemaTiposEntidade As tbSistemaTiposEntidade
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbTiposDocumentoSeries As tbTiposDocumentoSeries
    Public Overridable Property tbDocumentosStockAnexos As ICollection(Of tbDocumentosStockAnexos) = New HashSet(Of tbDocumentosStockAnexos)
    Public Overridable Property tbDocumentosStockLinhas As ICollection(Of tbDocumentosStockLinhas) = New HashSet(Of tbDocumentosStockLinhas)

End Class
