'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbEntidadesComparticipacoes
    Public Property ID As Long
    Public Property IDEntidade As Long
    Public Property IDTipoArtigo As Long
    Public Property IDTipoLente As Nullable(Of Long)
    Public Property PotenciaEsfericaDe As Nullable(Of Double)
    Public Property PotenciaEsfericaAte As Nullable(Of Double)
    Public Property PotenciaCilindricaDe As Nullable(Of Double)
    Public Property PotenciaCilindricaAte As Nullable(Of Double)
    Public Property PotenciaPrismaticaDe As Nullable(Of Double)
    Public Property PotenciaPrismaticaAte As Nullable(Of Double)
    Public Property ValorMaximo As Nullable(Of Double)
    Public Property Percentagem As Nullable(Of Double)
    Public Property Quantidade As Nullable(Of Double)
    Public Property Duracao As Nullable(Of Double)
    Public Property Ordem As Integer
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbEntidades As tbEntidades
    Public Overridable Property tbSistemaTiposLentes As tbSistemaTiposLentes
    Public Overridable Property tbTiposArtigos As tbTiposArtigos

End Class
