'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbFormasPagamento
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDTipoFormaPagamento As Long
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbClientes As ICollection(Of tbClientes) = New HashSet(Of tbClientes)
    Public Overridable Property tbDocumentosVendasFormasPagamento As ICollection(Of tbDocumentosVendasFormasPagamento) = New HashSet(Of tbDocumentosVendasFormasPagamento)
    Public Overridable Property tbSistemaTiposFormasPagamento As tbSistemaTiposFormasPagamento
    Public Overridable Property tbFormasPagamentoIdiomas As ICollection(Of tbFormasPagamentoIdiomas) = New HashSet(Of tbFormasPagamentoIdiomas)
    Public Overridable Property tbFornecedores As ICollection(Of tbFornecedores) = New HashSet(Of tbFornecedores)
    Public Overridable Property tbPagamentosComprasFormasPagamento As ICollection(Of tbPagamentosComprasFormasPagamento) = New HashSet(Of tbPagamentosComprasFormasPagamento)
    Public Overridable Property tbPagamentosVendasFormasPagamento As ICollection(Of tbPagamentosVendasFormasPagamento) = New HashSet(Of tbPagamentosVendasFormasPagamento)
    Public Overridable Property tbRecibosFormasPagamento As ICollection(Of tbRecibosFormasPagamento) = New HashSet(Of tbRecibosFormasPagamento)

End Class
