'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbFormasExpedicaoIdiomas
    Public Property ID As Long
    Public Property IDFormaExpedicao As Long
    Public Property IDIdioma As Long
    Public Property Descricao As String
    Public Property Ordem As Integer
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbFormasExpedicao As tbFormasExpedicao
    Public Overridable Property tbIdiomas As tbIdiomas

End Class
