'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbGamasLentes
    Public Property ID As Long
    Public Property IDModelo As Long
    Public Property IDTratamentoLente As Nullable(Of Long)
    Public Property Descentrado As Nullable(Of Boolean)
    Public Property DiamDe As String
    Public Property DiamAte As String
    Public Property PotEsfDe As Nullable(Of Double)
    Public Property PotEsfAte As Nullable(Of Double)
    Public Property PotCilDe As Nullable(Of Double)
    Public Property PotCilAte As Nullable(Of Double)
    Public Property Raio As String
    Public Property AdicaoDe As Nullable(Of Double)
    Public Property AdicaoAte As Nullable(Of Double)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbModelos As tbModelos
    Public Overridable Property tbTratamentosLentes As tbTratamentosLentes

End Class
