'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbIdiomas
    Public Property ID As Long
    Public Property Codigo As String
    Public Property IDCultura As Long
    Public Property Descricao As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArtigosIdiomas As ICollection(Of tbArtigosIdiomas) = New HashSet(Of tbArtigosIdiomas)
    Public Overridable Property tbClientes As ICollection(Of tbClientes) = New HashSet(Of tbClientes)
    Public Overridable Property tbComposicoesIdiomas As ICollection(Of tbComposicoesIdiomas) = New HashSet(Of tbComposicoesIdiomas)
    Public Overridable Property tbCondicoesPagamentoIdiomas As ICollection(Of tbCondicoesPagamentoIdiomas) = New HashSet(Of tbCondicoesPagamentoIdiomas)
    Public Overridable Property tbFormasExpedicaoIdiomas As ICollection(Of tbFormasExpedicaoIdiomas) = New HashSet(Of tbFormasExpedicaoIdiomas)
    Public Overridable Property tbFormasPagamentoIdiomas As ICollection(Of tbFormasPagamentoIdiomas) = New HashSet(Of tbFormasPagamentoIdiomas)
    Public Overridable Property tbFornecedores As ICollection(Of tbFornecedores) = New HashSet(Of tbFornecedores)
    Public Overridable Property tbSistemaIdiomas As tbSistemaIdiomas
    Public Overridable Property tbSegmentosMercadoIdiomas As ICollection(Of tbSegmentosMercadoIdiomas) = New HashSet(Of tbSegmentosMercadoIdiomas)
    Public Overridable Property tbSetoresAtividadeIdiomas As ICollection(Of tbSetoresAtividadeIdiomas) = New HashSet(Of tbSetoresAtividadeIdiomas)
    Public Overridable Property tbTiposDocumentoIdioma As ICollection(Of tbTiposDocumentoIdioma) = New HashSet(Of tbTiposDocumentoIdioma)

End Class
