'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbImpostoSelo
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDVerbaIS As Long
    Public Property Percentagem As Nullable(Of Double)
    Public Property Valor As Nullable(Of Double)
    Public Property LimiteMinimo As Nullable(Of Double)
    Public Property LimiteMaximo As Nullable(Of Double)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArtigos As ICollection(Of tbArtigos) = New HashSet(Of tbArtigos)
    Public Overridable Property tbSistemaVerbasIS As tbSistemaVerbasIS

End Class
