'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbIVA
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Taxa As Decimal
    Public Property IDTipoIva As Long
    Public Property IDCodigoIva As Nullable(Of Long)
    Public Property Mencao As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArtigos As ICollection(Of tbArtigos) = New HashSet(Of tbArtigos)
    Public Overridable Property tbDocumentosCompras As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosComprasLinhas As ICollection(Of tbDocumentosComprasLinhas) = New HashSet(Of tbDocumentosComprasLinhas)
    Public Overridable Property tbDocumentosStock As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStockLinhas As ICollection(Of tbDocumentosStockLinhas) = New HashSet(Of tbDocumentosStockLinhas)
    Public Overridable Property tbDocumentosVendas As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendasLinhas As ICollection(Of tbDocumentosVendasLinhas) = New HashSet(Of tbDocumentosVendasLinhas)
    Public Overridable Property tbSistemaCodigosIVA As tbSistemaCodigosIVA
    Public Overridable Property tbSistemaTiposIVA As tbSistemaTiposIVA
    Public Overridable Property tbIVADescontos As ICollection(Of tbIVADescontos) = New HashSet(Of tbIVADescontos)
    Public Overridable Property tbIVARegioes As ICollection(Of tbIVARegioes) = New HashSet(Of tbIVARegioes)
    Public Overridable Property tbIVARegioes1 As ICollection(Of tbIVARegioes) = New HashSet(Of tbIVARegioes)
    Public Overridable Property tbPagamentosCompras As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)

End Class
