'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbLojas
    Public Property ID As Long
    Public Property IDEmpresa As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDLojaSede As Long
    Public Property DescricaoLojaSede As String
    Public Property SedeGrupo As Boolean
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property EnderecoIP As String
    Public Property Cor As String
    Public Property Abertura As Nullable(Of Date)
    Public Property Fecho As Nullable(Of Date)

    Public Overridable Property tbAgendamento As ICollection(Of tbAgendamento) = New HashSet(Of tbAgendamento)
    Public Overridable Property tbArmazens As ICollection(Of tbArmazens) = New HashSet(Of tbArmazens)
    Public Overridable Property tbArtigosPrecos As ICollection(Of tbArtigosPrecos) = New HashSet(Of tbArtigosPrecos)
    Public Overridable Property tbBancos As ICollection(Of tbBancos) = New HashSet(Of tbBancos)
    Public Overridable Property tbClientes As ICollection(Of tbClientes) = New HashSet(Of tbClientes)
    Public Overridable Property tbClientesLojas As ICollection(Of tbClientesLojas) = New HashSet(Of tbClientesLojas)
    Public Overridable Property tbContasBancarias As ICollection(Of tbContasBancarias) = New HashSet(Of tbContasBancarias)
    Public Overridable Property tbContasCaixa As ICollection(Of tbContasCaixa) = New HashSet(Of tbContasCaixa)
    Public Overridable Property tbDocumentosCompras As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosCompras1 As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosStock As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStock1 As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosVendas As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendas1 As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendasFormasPagamento As ICollection(Of tbDocumentosVendasFormasPagamento) = New HashSet(Of tbDocumentosVendasFormasPagamento)
    Public Overridable Property tbEntidades As ICollection(Of tbEntidades) = New HashSet(Of tbEntidades)
    Public Overridable Property tbEntidadesLojas As ICollection(Of tbEntidadesLojas) = New HashSet(Of tbEntidadesLojas)
    Public Overridable Property tbExames As ICollection(Of tbExames) = New HashSet(Of tbExames)
    Public Overridable Property tbFornecedores As ICollection(Of tbFornecedores) = New HashSet(Of tbFornecedores)
    Public Overridable Property tbMapasVistas As ICollection(Of tbMapasVistas) = New HashSet(Of tbMapasVistas)
    Public Overridable Property tbMedicosTecnicos As ICollection(Of tbMedicosTecnicos) = New HashSet(Of tbMedicosTecnicos)
    Public Overridable Property tbPagamentosCompras As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbPagamentosComprasLinhas As ICollection(Of tbPagamentosComprasLinhas) = New HashSet(Of tbPagamentosComprasLinhas)
    Public Overridable Property tbPagamentosVendas As ICollection(Of tbPagamentosVendas) = New HashSet(Of tbPagamentosVendas)
    Public Overridable Property tbPagamentosVendasFormasPagamento As ICollection(Of tbPagamentosVendasFormasPagamento) = New HashSet(Of tbPagamentosVendasFormasPagamento)
    Public Overridable Property tbPagamentosVendasLinhas As ICollection(Of tbPagamentosVendasLinhas) = New HashSet(Of tbPagamentosVendasLinhas)
    Public Overridable Property tbParametrosContexto As ICollection(Of tbParametrosContexto) = New HashSet(Of tbParametrosContexto)
    Public Overridable Property tbParametrosLoja As ICollection(Of tbParametrosLoja) = New HashSet(Of tbParametrosLoja)
    Public Overridable Property tbParametrosLojaLinhas As ICollection(Of tbParametrosLojaLinhas) = New HashSet(Of tbParametrosLojaLinhas)
    Public Overridable Property tbPlaneamento As ICollection(Of tbPlaneamento) = New HashSet(Of tbPlaneamento)
    Public Overridable Property tbRazoes As ICollection(Of tbRazoes) = New HashSet(Of tbRazoes)
    Public Overridable Property tbRecibos As ICollection(Of tbRecibos) = New HashSet(Of tbRecibos)
    Public Overridable Property tbSAFT As ICollection(Of tbSAFT) = New HashSet(Of tbSAFT)
    Public Overridable Property tbTemplates As ICollection(Of tbTemplates) = New HashSet(Of tbTemplates)
    Public Overridable Property tbTiposConsultas As ICollection(Of tbTiposConsultas) = New HashSet(Of tbTiposConsultas)
    Public Overridable Property tbTiposDocumentoSeries As ICollection(Of tbTiposDocumentoSeries) = New HashSet(Of tbTiposDocumentoSeries)

End Class
