'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbMarcas
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property VariavelContabilidade As String
    Public Property AtualizaPrecos As Nullable(Of Boolean)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDSegmentoMarca As Nullable(Of Long)

    Public Overridable Property tbArtigos As ICollection(Of tbArtigos) = New HashSet(Of tbArtigos)
    Public Overridable Property tbCoresLentes As ICollection(Of tbCoresLentes) = New HashSet(Of tbCoresLentes)
    Public Overridable Property tbSegmentosMarcas As tbSegmentosMarcas
    Public Overridable Property tbModelos As ICollection(Of tbModelos) = New HashSet(Of tbModelos)
    Public Overridable Property tbSuplementosLentes As ICollection(Of tbSuplementosLentes) = New HashSet(Of tbSuplementosLentes)
    Public Overridable Property tbTratamentosLentes As ICollection(Of tbTratamentosLentes) = New HashSet(Of tbTratamentosLentes)

End Class
