'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbMensagemregistro
    Public Property ID As Long
    Public Property IDComunicacao As Long
    Public Property Request As String
    Public Property Response As String
    Public Property Status As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbComunicacao As tbComunicacao
    Public Overridable Property tbComunicacaoregistro As ICollection(Of tbComunicacaoregistro) = New HashSet(Of tbComunicacaoregistro)

End Class
