'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbModelos
    Public Property ID As Long
    Public Property IDMarca As Long
    Public Property IDTipoArtigo As Long
    Public Property IDTipoLente As Nullable(Of Long)
    Public Property IDMateriaLente As Nullable(Of Long)
    Public Property IDSuperficieLente As Nullable(Of Long)
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Stock As Boolean
    Public Property Fotocromatica As Boolean
    Public Property IndiceRefracao As Double
    Public Property NrABBE As String
    Public Property TransmissaoLuz As String
    Public Property Material As String
    Public Property UVA As String
    Public Property UVB As String
    Public Property Infravermelhos As String
    Public Property CodForn As String
    Public Property Referencia As String
    Public Property ModeloForn As String
    Public Property CodCor As String
    Public Property CodTratamento As String
    Public Property CodInstrucao As String
    Public Property Observacoes As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbAros As ICollection(Of tbAros) = New HashSet(Of tbAros)
    Public Overridable Property tbCoresLentes As ICollection(Of tbCoresLentes) = New HashSet(Of tbCoresLentes)
    Public Overridable Property tbGamasLentes As ICollection(Of tbGamasLentes) = New HashSet(Of tbGamasLentes)
    Public Overridable Property tbLentesContato As ICollection(Of tbLentesContato) = New HashSet(Of tbLentesContato)
    Public Overridable Property tbLentesOftalmicas As ICollection(Of tbLentesOftalmicas) = New HashSet(Of tbLentesOftalmicas)
    Public Overridable Property tbMarcas As tbMarcas
    Public Overridable Property tbSistemaMateriasLentes As tbSistemaMateriasLentes
    Public Overridable Property tbSistemaSuperficiesLentes As tbSistemaSuperficiesLentes
    Public Overridable Property tbSistemaTiposLentes As tbSistemaTiposLentes
    Public Overridable Property tbTiposArtigos As tbTiposArtigos
    Public Overridable Property tbOculosSol As ICollection(Of tbOculosSol) = New HashSet(Of tbOculosSol)
    Public Overridable Property tbPrecosLentes As ICollection(Of tbPrecosLentes) = New HashSet(Of tbPrecosLentes)
    Public Overridable Property tbSuplementosLentes As ICollection(Of tbSuplementosLentes) = New HashSet(Of tbSuplementosLentes)
    Public Overridable Property tbTratamentosLentes As ICollection(Of tbTratamentosLentes) = New HashSet(Of tbTratamentosLentes)

End Class
