'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbMoedas
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property TaxaConversao As Double
    Public Property DescricaoDecimal As String
    Public Property DescricaoInteira As String
    Public Property CasasDecimaisTotais As Nullable(Of Byte)
    Public Property CasasDecimaisIva As Nullable(Of Byte)
    Public Property CasasDecimaisPrecosUnitarios As Nullable(Of Byte)
    Public Property IDSistemaMoeda As Long
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Simbolo As String

    Public Overridable Property tbCCStockArtigos As ICollection(Of tbCCStockArtigos) = New HashSet(Of tbCCStockArtigos)
    Public Overridable Property tbClientes As ICollection(Of tbClientes) = New HashSet(Of tbClientes)
    Public Overridable Property tbContasBancarias As ICollection(Of tbContasBancarias) = New HashSet(Of tbContasBancarias)
    Public Overridable Property tbDocumentosCompras As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosStock As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosVendas As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbFornecedores As ICollection(Of tbFornecedores) = New HashSet(Of tbFornecedores)
    Public Overridable Property tbSistemaMoedas As tbSistemaMoedas
    Public Overridable Property tbPagamentosCompras As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbPagamentosComprasFormasPagamento As ICollection(Of tbPagamentosComprasFormasPagamento) = New HashSet(Of tbPagamentosComprasFormasPagamento)
    Public Overridable Property tbPagamentosComprasLinhas As ICollection(Of tbPagamentosComprasLinhas) = New HashSet(Of tbPagamentosComprasLinhas)
    Public Overridable Property tbPagamentosVendas As ICollection(Of tbPagamentosVendas) = New HashSet(Of tbPagamentosVendas)
    Public Overridable Property tbPagamentosVendasLinhas As ICollection(Of tbPagamentosVendasLinhas) = New HashSet(Of tbPagamentosVendasLinhas)
    Public Overridable Property tbParametrosEmpresa As ICollection(Of tbParametrosEmpresa) = New HashSet(Of tbParametrosEmpresa)
    Public Overridable Property tbParametrosLoja As ICollection(Of tbParametrosLoja) = New HashSet(Of tbParametrosLoja)
    Public Overridable Property tbRecibos As ICollection(Of tbRecibos) = New HashSet(Of tbRecibos)
    Public Overridable Property tbRecibosFormasPagamento As ICollection(Of tbRecibosFormasPagamento) = New HashSet(Of tbRecibosFormasPagamento)
    Public Overridable Property tbRecibosLinhas As ICollection(Of tbRecibosLinhas) = New HashSet(Of tbRecibosLinhas)

End Class
