'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbParametrizacaoConsentimentosCamposEntidade
    Public Property ID As Long
    Public Property IDSistemaFuncionalidadesConsentimento As Integer
    Public Property IDParametrizacaoConsentimento As Nullable(Of Long)
    Public Property Tabela As String
    Public Property NomeCampoChave As String
    Public Property NomeCampo As String
    Public Property DescricaoCampo As String
    Public Property TipoCampo As String
    Public Property TamanhoMaximoCampo As String
    Public Property ExpressaoLista As String
    Public Property ForeignKey As Boolean
    Public Property TabelaLeftJoin As String
    Public Property CampoLeftJoin As String
    Public Property ExpressaoLeftJoin As String
    Public Property AliasLeftJoin As String
    Public Property NumeroLinhaPosicionado As Long
    Public Property OrdemPosicionado As Long
    Public Property PercentagemOcupaLinha As Nullable(Of Double)
    Public Property CondicaoVisibilidade As String
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbParametrizacaoConsentimentos As tbParametrizacaoConsentimentos
    Public Overridable Property tbSistemaFuncionalidadesConsentimento As tbSistemaFuncionalidadesConsentimento

End Class
