'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbParametrosEmpresa
    Public Property ID As Long
    Public Property IDMoedaDefeito As Nullable(Of Long)
    Public Property Morada As String
    Public Property Foto As String
    Public Property FotoCaminho As String
    Public Property DesignacaoComercial As String
    Public Property CodigoPostal As String
    Public Property Localidade As String
    Public Property Concelho As String
    Public Property Distrito As String
    Public Property IDPais As Nullable(Of Long)
    Public Property Telefone As String
    Public Property Fax As String
    Public Property Email As String
    Public Property WebSite As String
    Public Property NIF As String
    Public Property ConservatoriaRegistoComercial As String
    Public Property NumeroRegistoComercial As String
    Public Property CapitalSocial As String
    Public Property IDIdiomaBase As Nullable(Of Long)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDEmpresa As Long
    Public Property CasasDecimaisPercentagem As Nullable(Of Byte)
    Public Property IDPaisesDesc As Nullable(Of Long)

    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbPaises As tbPaises
    Public Overridable Property tbParametrosContexto As ICollection(Of tbParametrosContexto) = New HashSet(Of tbParametrosContexto)
    Public Overridable Property tbSistemaIdiomas As tbSistemaIdiomas
    Public Overridable Property tbSistemaSiglasPaises As tbSistemaSiglasPaises
    Public Overridable Property tbParametrosEmpresaCAE As ICollection(Of tbParametrosEmpresaCAE) = New HashSet(Of tbParametrosEmpresaCAE)

End Class
