'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbPagamentosVendasLinhas
    Public Property ID As Long
    Public Property IDPagamentoVenda As Long
    Public Property IDTipoDocumento As Long
    Public Property IDTiposDocumentoSeries As Long
    Public Property IDDocumentoVenda As Long
    Public Property IDEntidade As Long
    Public Property NumeroDocumento As Nullable(Of Long)
    Public Property DataDocumento As Date
    Public Property DataVencimento As Date
    Public Property Documento As String
    Public Property TotalMoedaDocumento As Nullable(Of Double)
    Public Property ValorPendente As Nullable(Of Double)
    Public Property TotalMoeda As Nullable(Of Double)
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property ValorPago As Nullable(Of Double)
    Public Property Ordem As Nullable(Of Integer)
    Public Property IDLoja As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbClientes As tbClientes
    Public Overridable Property tbDocumentosVendas As tbDocumentosVendas
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbPagamentosVendas As tbPagamentosVendas
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbTiposDocumentoSeries As tbTiposDocumentoSeries

End Class
