'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbParametrosContexto
    Public Property ID As Long
    Public Property IDPai As Nullable(Of Long)
    Public Property Codigo As String
    Public Property CodigoPai As String
    Public Property Descricao As String
    Public Property Accao As String
    Public Property MostraConteudo As Boolean
    Public Property IDParametrosEmpresa As Nullable(Of Long)
    Public Property IDLoja As Nullable(Of Long)
    Public Property Ordem As Integer
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbParametrosCamposContexto As ICollection(Of tbParametrosCamposContexto) = New HashSet(Of tbParametrosCamposContexto)
    Public Overridable Property tbParametrosContexto1 As ICollection(Of tbParametrosContexto) = New HashSet(Of tbParametrosContexto)
    Public Overridable Property tbParametrosContexto2 As tbParametrosContexto
    Public Overridable Property tbParametrosEmpresa As tbParametrosEmpresa

End Class
