'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbPagamentosVendasFormasPagamento
    Public Property ID As Long
    Public Property IDPagamentoVenda As Long
    Public Property IDFormaPagamento As Long
    Public Property TotalMoeda As Nullable(Of Double)
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property Valor As Nullable(Of Double)
    Public Property Ordem As Nullable(Of Integer)
    Public Property IDLoja As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbFormasPagamento As tbFormasPagamento
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbPagamentosVendas As tbPagamentosVendas

End Class
