'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbParametrosCamposContexto
    Public Property ID As Long
    Public Property IDParametroContexto As Long
    Public Property CodigoCampo As String
    Public Property DescricaoCampo As String
    Public Property TipoCondicionante As Nullable(Of Byte)
    Public Property IDTipoDados As Long
    Public Property ConteudoLista As String
    Public Property ValorCampo As String
    Public Property Accao As String
    Public Property AccaoExtra As String
    Public Property Filtro As String
    Public Property ValorMax As String
    Public Property ValorMin As String
    Public Property ValorReadOnly As Boolean
    Public Property Ordem As Integer
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbCondicionantes As ICollection(Of tbCondicionantes) = New HashSet(Of tbCondicionantes)
    Public Overridable Property tbParametrosContexto As tbParametrosContexto
    Public Overridable Property tbTiposDados As tbTiposDados

End Class
