'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbPagamentosVendas
    Public Property ID As Long
    Public Property Numero As Nullable(Of Long)
    Public Property Data As Date
    Public Property Descricao As String
    Public Property TotalMoeda As Nullable(Of Double)
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property ValorEntregue As Nullable(Of Double)
    Public Property Troco As Nullable(Of Double)
    Public Property IDLoja As Nullable(Of Long)
    Public Property CodigoTipoEstado As String
    Public Property Observacoes As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDContaCaixa As Nullable(Of Long)

    Public Overridable Property tbContasCaixa As tbContasCaixa
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbPagamentosVendasFormasPagamento As ICollection(Of tbPagamentosVendasFormasPagamento) = New HashSet(Of tbPagamentosVendasFormasPagamento)
    Public Overridable Property tbPagamentosVendasLinhas As ICollection(Of tbPagamentosVendasLinhas) = New HashSet(Of tbPagamentosVendasLinhas)
    Public Overridable Property tbRecibos As ICollection(Of tbRecibos) = New HashSet(Of tbRecibos)

End Class
