'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbPlaneamento
    Public Property ID As Long
    Public Property Start As Date
    Public Property [End] As Date
    Public Property IsAllDay As Boolean
    Public Property RecurrenceRule As String
    Public Property RecurrenceException As String
    Public Property StartTimezone As String
    Public Property EndTimezone As String
    Public Property IDLoja As Long
    Public Property IDMedicoTecnico As Long
    Public Property Observacoes As String
    Public Property Nome As String
    Public Property Contacto As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMedicosTecnicos As tbMedicosTecnicos

End Class
