'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbRecibosLinhas
    Public Property ID As Long
    Public Property IDRecibo As Long
    Public Property IDTipoDocumento As Long
    Public Property IDTiposDocumentoSeries As Long
    Public Property IDDocumentoVenda As Long
    Public Property NumeroDocumento As Nullable(Of Long)
    Public Property DataDocumento As Date
    Public Property DataVencimento As Nullable(Of Date)
    Public Property Documento As String
    Public Property IDEntidade As Nullable(Of Long)
    Public Property NomeFiscal As String
    Public Property MoradaFiscal As String
    Public Property IDCodigoPostalFiscal As Nullable(Of Long)
    Public Property IDConcelhoFiscal As Nullable(Of Long)
    Public Property IDDistritoFiscal As Nullable(Of Long)
    Public Property CodigoPostalFiscal As String
    Public Property DescricaoCodigoPostalFiscal As String
    Public Property DescricaoConcelhoFiscal As String
    Public Property DescricaoDistritoFiscal As String
    Public Property ContribuinteFiscal As String
    Public Property SiglaPaisFiscal As String
    Public Property TotalMoedaDocumento As Nullable(Of Double)
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property ValorPago As Nullable(Of Double)
    Public Property ValorIncidencia As Nullable(Of Double)
    Public Property ValorIva As Nullable(Of Double)
    Public Property DocumentoOrigem As String
    Public Property DataDocOrigem As Nullable(Of Date)
    Public Property Adiantamento As Nullable(Of Boolean)
    Public Property Ordem As Nullable(Of Integer)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property TaxaDocOriginal As Nullable(Of Double)
    Public Property ValorDifCambialMoedaReferencia As Nullable(Of Double)

    Public Overridable Property tbClientes As tbClientes
    Public Overridable Property tbCodigosPostais As tbCodigosPostais
    Public Overridable Property tbConcelhos As tbConcelhos
    Public Overridable Property tbDistritos As tbDistritos
    Public Overridable Property tbDocumentosVendas As tbDocumentosVendas
    Public Overridable Property tbMoedas As tbMoedas
    Public Overridable Property tbRecibos As tbRecibos
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbTiposDocumentoSeries As tbTiposDocumentoSeries
    Public Overridable Property tbRecibosLinhasTaxas As ICollection(Of tbRecibosLinhasTaxas) = New HashSet(Of tbRecibosLinhasTaxas)

End Class
