'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSemafroGereStock
    Public Property ID As Long
    Public Property IDDocumento As Nullable(Of Long)
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property Accao As Nullable(Of Integer)
    Public Property TabelaCabecalho As String
    Public Property TabelaLinhas As String
    Public Property TabelaLinhasDist As String
    Public Property CampoRelTabelaLinhasCab As String
    Public Property CampoRelTabelaLinhasDistLinhas As String
    Public Property Utilizador As String
    Public Property F3MMarcador As Byte()

End Class
