'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbServicosFases
    Public Property ID As Long
    Public Property IDTipoFase As Long
    Public Property IDServico As Long
    Public Property IDTipoServico As Nullable(Of Long)
    Public Property Data As Nullable(Of Date)
    Public Property Observacoes As String
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbServicos As tbServicos
    Public Overridable Property tbSistemaTiposServicos As tbSistemaTiposServicos
    Public Overridable Property tbTiposFases As tbTiposFases

End Class
