'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaTiposDocumento
    Public Property ID As Long
    Public Property Tipo As String
    Public Property Descricao As String
    Public Property IDModulo As Long
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property TipoFiscal As Boolean
    Public Property ActivaPredefTipoDoc As Boolean
    Public Property Codigo As String

    Public Overridable Property tbMapasVistas As ICollection(Of tbMapasVistas) = New HashSet(Of tbMapasVistas)
    Public Overridable Property tbSistemaModulos As tbSistemaModulos
    Public Overridable Property tbSistemaTiposDocumentoColunasAutomaticas As ICollection(Of tbSistemaTiposDocumentoColunasAutomaticas) = New HashSet(Of tbSistemaTiposDocumentoColunasAutomaticas)
    Public Overridable Property tbSistemaTiposDocumentoFiscal As ICollection(Of tbSistemaTiposDocumentoFiscal) = New HashSet(Of tbSistemaTiposDocumentoFiscal)
    Public Overridable Property tbTiposDocumento As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)

End Class
