'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaComunicacaoSmsTemplatesValores
    Public Property ID As Long
    Public Property TipoComponente As String
    Public Property Ordem As Nullable(Of Long)
    Public Property MinValue As String
    Public Property MaxValue As String
    Public Property DefaultValue As String
    Public Property SqlQuery As String
    Public Property Placeholder As String
    Public Property IDSistemaComunicacaoSmsTemplatesCondicoes As Nullable(Of Long)
    Public Property CssClasses As String
    Public Property SqlQueryWhere As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property UnionSqlQueryWhere As Boolean

    Public Overridable Property tbComunicacaoSmsTemplatesValores As ICollection(Of tbComunicacaoSmsTemplatesValores) = New HashSet(Of tbComunicacaoSmsTemplatesValores)
    Public Overridable Property tbSistemaComunicacaoSmsTemplatesCondicoes As tbSistemaComunicacaoSmsTemplatesCondicoes

End Class
