'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaTiposDocumentoColunasAutomaticas
    Public Property ID As Long
    Public Property IDSistemaTipoDocumento As Long
    Public Property Coluna As String
    Public Property ChaveColunaTraducao As String
    Public Property IDPai As Nullable(Of Long)
    Public Property ControladorExtra As String
    Public Property Controlador As String
    Public Property CampoTexto As String
    Public Property EnviaParametros As String
    Public Property Validador As String
    Public Property IDTipoEditor As Nullable(Of Long)
    Public Property Width As Nullable(Of Double)
    Public Property Maximo As Nullable(Of Double)
    Public Property Minimo As Nullable(Of Double)
    Public Property TamMaximo As Nullable(Of Double)
    Public Property CasasDecimais As Nullable(Of Byte)
    Public Property Editavel As Boolean
    Public Property Obrigatoria As Boolean
    Public Property NaoPermiteNegativos As Boolean
    Public Property ElementoUnico As Boolean
    Public Property Visivel As Boolean
    Public Property CamposPreencher As String
    Public Property Ordem As Integer
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbSistemaTiposDocumento As tbSistemaTiposDocumento
    Public Overridable Property tbSistemaTiposDocumentoColunasAutomaticas1 As ICollection(Of tbSistemaTiposDocumentoColunasAutomaticas) = New HashSet(Of tbSistemaTiposDocumentoColunasAutomaticas)
    Public Overridable Property tbSistemaTiposDocumentoColunasAutomaticas2 As tbSistemaTiposDocumentoColunasAutomaticas
    Public Overridable Property tbTiposDados As tbTiposDados

End Class
