'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaTiposAnexos
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDEntidadeF3M As Long
    Public Property IDTipoExtensaoFicheiro As Long
    Public Property TamanhoMaximoFicheiro As Nullable(Of Integer)
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArtigosAnexos As ICollection(Of tbArtigosAnexos) = New HashSet(Of tbArtigosAnexos)
    Public Overridable Property tbClientesAnexos As ICollection(Of tbClientesAnexos) = New HashSet(Of tbClientesAnexos)
    Public Overridable Property tbComunicacaoAutoridadeTributariaAnexos As ICollection(Of tbComunicacaoAutoridadeTributariaAnexos) = New HashSet(Of tbComunicacaoAutoridadeTributariaAnexos)
    Public Overridable Property tbDocumentosComprasAnexos As ICollection(Of tbDocumentosComprasAnexos) = New HashSet(Of tbDocumentosComprasAnexos)
    Public Overridable Property tbDocumentosStockAnexos As ICollection(Of tbDocumentosStockAnexos) = New HashSet(Of tbDocumentosStockAnexos)
    Public Overridable Property tbDocumentosStockContagemAnexos As ICollection(Of tbDocumentosStockContagemAnexos) = New HashSet(Of tbDocumentosStockContagemAnexos)
    Public Overridable Property tbDocumentosVendasAnexos As ICollection(Of tbDocumentosVendasAnexos) = New HashSet(Of tbDocumentosVendasAnexos)
    Public Overridable Property tbEntidadesAnexos As ICollection(Of tbEntidadesAnexos) = New HashSet(Of tbEntidadesAnexos)
    Public Overridable Property tbExamesAnexos As ICollection(Of tbExamesAnexos) = New HashSet(Of tbExamesAnexos)
    Public Overridable Property tbFornecedoresAnexos As ICollection(Of tbFornecedoresAnexos) = New HashSet(Of tbFornecedoresAnexos)
    Public Overridable Property tbMedicosTecnicosAnexos As ICollection(Of tbMedicosTecnicosAnexos) = New HashSet(Of tbMedicosTecnicosAnexos)
    Public Overridable Property tbPagamentosComprasAnexos As ICollection(Of tbPagamentosComprasAnexos) = New HashSet(Of tbPagamentosComprasAnexos)
    Public Overridable Property tbSistemaEntidadesF3M As tbSistemaEntidadesF3M
    Public Overridable Property tbSistemaTiposExtensoesFicheiros As tbSistemaTiposExtensoesFicheiros

End Class
