'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaModulos
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Ordem As Integer
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property TiposDocumentos As Boolean

    Public Overridable Property tbMapasVistas As ICollection(Of tbMapasVistas) = New HashSet(Of tbMapasVistas)
    Public Overridable Property tbSistemaTiposDocumento As ICollection(Of tbSistemaTiposDocumento) = New HashSet(Of tbSistemaTiposDocumento)
    Public Overridable Property tbSistemaTiposEntidadeModulos As ICollection(Of tbSistemaTiposEntidadeModulos) = New HashSet(Of tbSistemaTiposEntidadeModulos)
    Public Overridable Property tbTiposDocumento As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)

End Class
