'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaTiposEntidadeModulos
    Public Property ID As Long
    Public Property IDSistemaTiposEntidade As Long
    Public Property IDSistemaModulos As Long
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbSistemaModulos As tbSistemaModulos
    Public Overridable Property tbSistemaTiposEntidade As tbSistemaTiposEntidade
    Public Overridable Property tbTiposDocumentoTipEntPermDoc As ICollection(Of tbTiposDocumentoTipEntPermDoc) = New HashSet(Of tbTiposDocumentoTipEntPermDoc)

End Class
