'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSistemaAcoes
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbMedicosTecnicos As ICollection(Of tbMedicosTecnicos) = New HashSet(Of tbMedicosTecnicos)
    Public Overridable Property tbTiposDocumento As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)
    Public Overridable Property tbTiposDocumento1 As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)
    Public Overridable Property tbTiposDocumento2 As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)
    Public Overridable Property tbTiposDocumento3 As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)
    Public Overridable Property tbTiposDocumento4 As ICollection(Of tbTiposDocumento) = New HashSet(Of tbTiposDocumento)

End Class
