'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbStockArtigosNecessidades
    Public Property ID As Long
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDDocumento As Nullable(Of Long)
    Public Property IDLinhaDocumento As Nullable(Of Long)
    Public Property IDOrdemFabrico As Nullable(Of Long)
    Public Property IDEncomenda As Nullable(Of Long)
    Public Property Documento As String
    Public Property IDArtigoPA As Nullable(Of Long)
    Public Property IDArtigo As Long
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDArmazem As Nullable(Of Long)
    Public Property IDArmazemLocalizacao As Nullable(Of Long)
    Public Property IDArtigoLote As Nullable(Of Long)
    Public Property IDArtigoNumeroSerie As Nullable(Of Long)
    Public Property IDArtigoDimensao As Nullable(Of Long)
    Public Property IDDimensaolinha1 As Nullable(Of Long)
    Public Property IDDimensaolinha2 As Nullable(Of Long)
    Public Property QtdStockReservado As Nullable(Of Double)
    Public Property QtdStockReservado2 As Nullable(Of Double)
    Public Property QtdStockRequisitado As Nullable(Of Double)
    Public Property QtdStockRequisitado2 As Nullable(Of Double)
    Public Property QtdStockRequisitadoPnd As Nullable(Of Double)
    Public Property QtdStockRequisitadoPnd2 As Nullable(Of Double)
    Public Property QtdStockConsumido As Nullable(Of Double)
    Public Property QtdStockConsumido2 As Nullable(Of Double)
    Public Property IDArtigoPara As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbArmazens As tbArmazens
    Public Overridable Property tbArmazensLocalizacoes As tbArmazensLocalizacoes
    Public Overridable Property tbArtigos As tbArtigos
    Public Overridable Property tbArtigos1 As tbArtigos
    Public Overridable Property tbArtigos2 As tbArtigos
    Public Overridable Property tbArtigosDimensoes As tbArtigosDimensoes
    Public Overridable Property tbArtigosLotes As tbArtigosLotes
    Public Overridable Property tbArtigosNumerosSeries As tbArtigosNumerosSeries

End Class
