'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbSuplementosLentes
    Public Property ID As Long
    Public Property IDMarca As Long
    Public Property IDModelo As Nullable(Of Long)
    Public Property IDTipoLente As Long
    Public Property IDMateriaLente As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Cor As Nullable(Of Boolean)
    Public Property PrecoVenda As Nullable(Of Double)
    Public Property PrecoCusto As Nullable(Of Double)
    Public Property CodForn As String
    Public Property Referencia As String
    Public Property ModeloForn As String
    Public Property Observacoes As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbLentesOftalmicasSuplementos As ICollection(Of tbLentesOftalmicasSuplementos) = New HashSet(Of tbLentesOftalmicasSuplementos)
    Public Overridable Property tbMarcas As tbMarcas
    Public Overridable Property tbModelos As tbModelos
    Public Overridable Property tbSistemaMateriasLentes As tbSistemaMateriasLentes
    Public Overridable Property tbSistemaTiposLentes As tbSistemaTiposLentes

End Class
