'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbTemplates
    Public Property ID As Long
    Public Property IDSistemaTipoTemplate As Long
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDLoja As Long
    Public Property Descricao As String
    Public Property Codigo As String

    Public Overridable Property tbExames As ICollection(Of tbExames) = New HashSet(Of tbExames)
    Public Overridable Property tbExamesTemplate As ICollection(Of tbExamesTemplate) = New HashSet(Of tbExamesTemplate)
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMedicosTecnicos As ICollection(Of tbMedicosTecnicos) = New HashSet(Of tbMedicosTecnicos)
    Public Overridable Property tbTiposConsultas As ICollection(Of tbTiposConsultas) = New HashSet(Of tbTiposConsultas)

End Class
