'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbTiposFases
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Ordem As Integer
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDSistemaClassificacoesTiposArtigos As Nullable(Of Long)
    Public Property IDSistemaTiposOlhos As Nullable(Of Long)
    Public Property IDSistemaTiposFases As Nullable(Of Long)

    Public Overridable Property tbServicosFases As ICollection(Of tbServicosFases) = New HashSet(Of tbServicosFases)
    Public Overridable Property tbSistemaClassificacoesTiposArtigos As tbSistemaClassificacoesTiposArtigos
    Public Overridable Property tbSistemaTiposFases As tbSistemaTiposFases
    Public Overridable Property tbSistemaTiposOlhos As tbSistemaTiposOlhos

End Class
