'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbTiposDocumentoTipEntPermDoc
    Public Property ID As Long
    Public Property IDTiposDocumento As Long
    Public Property IDSistemaTiposEntidadeModulos As Long
    Public Property Sistema As Boolean
    Public Property Ativo As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Long
    Public Property ContadorDoc As Long

    Public Overridable Property tbSistemaTiposEntidadeModulos As tbSistemaTiposEntidadeModulos
    Public Overridable Property tbTiposDocumento As tbTiposDocumento

End Class
