'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbTiposConsultas
    Public Property ID As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property IDTemplate As Long
    Public Property IDLoja As Long
    Public Property IDMapaVista1 As Nullable(Of Long)
    Public Property IDMapaVista2 As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()

    Public Overridable Property tbExames As ICollection(Of tbExames) = New HashSet(Of tbExames)
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMapasVistas As tbMapasVistas
    Public Overridable Property tbMapasVistas1 As tbMapasVistas
    Public Overridable Property tbMedicosTecnicos As ICollection(Of tbMedicosTecnicos) = New HashSet(Of tbMedicosTecnicos)
    Public Overridable Property tbTemplates As tbTemplates

End Class
