'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbTiposDocumentoSeries
    Public Property ID As Long
    Public Property CodigoSerie As String
    Public Property DescricaoSerie As String
    Public Property SugeridaPorDefeito As Boolean
    Public Property IDTiposDocumento As Long
    Public Property Sistema As Boolean
    Public Property AtivoSerie As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property Ordem As Long
    Public Property CalculaComissoesSerie As Boolean
    Public Property AnalisesEstatisticasSerie As Boolean
    Public Property IVAIncluido As Boolean
    Public Property IVARegimeCaixa As Boolean
    Public Property DataInicial As Nullable(Of Date)
    Public Property DataFinal As Nullable(Of Date)
    Public Property DataUltimoDoc As Nullable(Of Date)
    Public Property NumUltimoDoc As Nullable(Of Long)
    Public Property IDSistemaTiposDocumentoOrigem As Nullable(Of Long)
    Public Property IDSistemaTiposDocumentoComunicacao As Nullable(Of Long)
    Public Property IDParametrosEmpresaCAE As Nullable(Of Long)
    Public Property NumeroVias As Nullable(Of Long)
    Public Property IDMapasVistas As Nullable(Of Long)
    Public Property IDLoja As Nullable(Of Long)
    Public Property ATCodValidacaoSerie As String
    Public Property Ativo As Nullable(Of Boolean)

    Public Overridable Property tbATEstadoComunicacao As ICollection(Of tbATEstadoComunicacao) = New HashSet(Of tbATEstadoComunicacao)
    Public Overridable Property tbCCStockArtigos As ICollection(Of tbCCStockArtigos) = New HashSet(Of tbCCStockArtigos)
    Public Overridable Property tbCCStockArtigos1 As ICollection(Of tbCCStockArtigos) = New HashSet(Of tbCCStockArtigos)
    Public Overridable Property tbDocumentosCompras As ICollection(Of tbDocumentosCompras) = New HashSet(Of tbDocumentosCompras)
    Public Overridable Property tbDocumentosComprasLinhas As ICollection(Of tbDocumentosComprasLinhas) = New HashSet(Of tbDocumentosComprasLinhas)
    Public Overridable Property tbDocumentosStock As ICollection(Of tbDocumentosStock) = New HashSet(Of tbDocumentosStock)
    Public Overridable Property tbDocumentosStockContagem As ICollection(Of tbDocumentosStockContagem) = New HashSet(Of tbDocumentosStockContagem)
    Public Overridable Property tbDocumentosStockLinhas As ICollection(Of tbDocumentosStockLinhas) = New HashSet(Of tbDocumentosStockLinhas)
    Public Overridable Property tbDocumentosVendas As ICollection(Of tbDocumentosVendas) = New HashSet(Of tbDocumentosVendas)
    Public Overridable Property tbDocumentosVendasLinhas As ICollection(Of tbDocumentosVendasLinhas) = New HashSet(Of tbDocumentosVendasLinhas)
    Public Overridable Property tbLojas As tbLojas
    Public Overridable Property tbMapasVistas As tbMapasVistas
    Public Overridable Property tbPagamentosCompras As ICollection(Of tbPagamentosCompras) = New HashSet(Of tbPagamentosCompras)
    Public Overridable Property tbPagamentosComprasLinhas As ICollection(Of tbPagamentosComprasLinhas) = New HashSet(Of tbPagamentosComprasLinhas)
    Public Overridable Property tbPagamentosVendasLinhas As ICollection(Of tbPagamentosVendasLinhas) = New HashSet(Of tbPagamentosVendasLinhas)
    Public Overridable Property tbParametrosEmpresaCAE As tbParametrosEmpresaCAE
    Public Overridable Property tbRecibos As ICollection(Of tbRecibos) = New HashSet(Of tbRecibos)
    Public Overridable Property tbRecibosLinhas As ICollection(Of tbRecibosLinhas) = New HashSet(Of tbRecibosLinhas)
    Public Overridable Property tbSistemaTiposDocumentoComunicacao As tbSistemaTiposDocumentoComunicacao
    Public Overridable Property tbSistemaTiposDocumentoOrigem As tbSistemaTiposDocumentoOrigem
    Public Overridable Property tbTiposDocumento As tbTiposDocumento
    Public Overridable Property tbControloDocumentos As ICollection(Of tbControloDocumentos) = New HashSet(Of tbControloDocumentos)
    Public Overridable Property tbTiposDocumentoSeriesPermissoes As ICollection(Of tbTiposDocumentoSeriesPermissoes) = New HashSet(Of tbTiposDocumentoSeriesPermissoes)

End Class
