'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbTratamentosLentes
    Public Property ID As Long
    Public Property IDMarca As Long
    Public Property IDModelo As Long
    Public Property Codigo As String
    Public Property Descricao As String
    Public Property Cor As Nullable(Of Boolean)
    Public Property CodForn As String
    Public Property Referencia As String
    Public Property ModeloForn As String
    Public Property Observacoes As String
    Public Property Ativo As Boolean
    Public Property Sistema As Boolean
    Public Property DataCriacao As Date
    Public Property UtilizadorCriacao As String
    Public Property DataAlteracao As Nullable(Of Date)
    Public Property UtilizadorAlteracao As String
    Public Property F3MMarcador As Byte()
    Public Property IDTipo As Nullable(Of Long)

    Public Overridable Property tbGamasLentes As ICollection(Of tbGamasLentes) = New HashSet(Of tbGamasLentes)
    Public Overridable Property tbLentesOftalmicas As ICollection(Of tbLentesOftalmicas) = New HashSet(Of tbLentesOftalmicas)
    Public Overridable Property tbMarcas As tbMarcas
    Public Overridable Property tbModelos As tbModelos
    Public Overridable Property tbPrecosLentes As ICollection(Of tbPrecosLentes) = New HashSet(Of tbPrecosLentes)
    Public Overridable Property tbTiposTratamentosLentes As tbTiposTratamentosLentes

End Class
