'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwArtigos
    Public Property tipodoc As String
    Public Property IDDocumento As Long
    Public Property Quantidade As Nullable(Of Double)
    Public Property ValorComIva As Nullable(Of Double)
    Public Property Codigo As String
    Public Property CodigoBarras As String
    Public Property CodigoBarrasFornecedor As String
    Public Property ReferenciaFornecedor As String
    Public Property ValorComIva2 As Double
    Public Property DescricaoMarca As String

End Class
