'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwCCArtigos
    Public Property Documento As String
    Public Property DocumentoOrigem As String
    Public Property NumeroDocumento As String
    Public Property DataDocumento As Nullable(Of Date)
    Public Property CodigoArtigo As String
    Public Property DescricaoArtigo As String
    Public Property Ativo As Nullable(Of Boolean)
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property CodigoArmazem As String
    Public Property DescricaoArmazem As String
    Public Property CodigoLocalizacao As String
    Public Property DescricaoLocalizacao As String
    Public Property CodigoLote As String
    Public Property DescricaoLote As String
    Public Property DescricaoTipoDocumento As String
    Public Property DescricaoTipoArtigo As String
    Public Property CodigoComposicao As String
    Public Property DescricaoComposicao As String
    Public Property CodigoCor As String
    Public Property CorGenerica As String
    Public Property CodigoCF As String
    Public Property DescricaoCF As String
    Public Property DescricaoDimensaoLinha1 As String
    Public Property DescricaoDimensaoLinha2 As String
    Public Property Natureza As String
    Public Property QtdStockAtual As Nullable(Of Double)
    Public Property QtdStockAnterior As Nullable(Of Double)
    Public Property PCMAtualMoedaRef As Double
    Public Property PCMAnteriorMoedaRef As Double
    Public Property QtdLinhaStock As Nullable(Of Double)
    Public Property QuantidadeStock As Double
    Public Property QtdLinhaStock2 As Nullable(Of Double)
    Public Property QuantidadeStock2 As Double
    Public Property PrecoUnitarioMoedaRef As Double
    Public Property RecalcularCustoMedio As Boolean
    Public Property DataControloInterno As Nullable(Of Date)

End Class
