'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwCCFornecedores
    Public Property CodigoFornecedor As String
    Public Property NomeFiscal As String
    Public Property IDEntidade As Nullable(Of Long)
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDTipoDocumentoSeries As Nullable(Of Long)
    Public Property NumeroDocumento As String
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Documento As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Natureza As String
    Public Property TotalMoeda As Nullable(Of Double)
    Public Property Valor As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property Saldo As Double
    Public Property tbMoedas_Descricao As String
    Public Property tbMoedas_Simbolo As String
    Public Property tbMoedas_CasasDecimaisTotais As Nullable(Of Byte)
    Public Property Saldonumcasasdecimais As Nullable(Of Byte)
    Public Property TotalMoedanumcasasdecimais As Nullable(Of Byte)
    Public Property TotalMoedaReferencianumcasasdecimais As Nullable(Of Byte)
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property CodigoTipoDocumento As String
    Public Property DescricaoTipoDocumento As String

End Class
