'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwMapaIvaVendas
    Public Property ID As Long
    Public Property IDLoja As Nullable(Of Long)
    Public Property NomeFiscal As String
    Public Property IDEntidade As Nullable(Of Long)
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDTiposDocumentoSeries As Nullable(Of Long)
    Public Property NumeroDocumento As Nullable(Of Long)
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Utilizador As String
    Public Property Documento As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property Ativo As Boolean
    Public Property TaxaIva As Nullable(Of Double)
    Public Property IDTaxaIva As Nullable(Of Long)
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property CodigoCliente As String
    Public Property NContribuinte As String
    Public Property CodigoTipoDocumento As String
    Public Property DescricaoTipoDocumento As String
    Public Property CodigoIva As String
    Public Property CodigoCampanha As String
    Public Property CodigoEstado As String
    Public Property DescricaoEstado As String
    Public Property Natureza As String
    Public Property ValorIncidencia As Nullable(Of Decimal)
    Public Property ValorIVA As Nullable(Of Decimal)
    Public Property Valor As Nullable(Of Decimal)
    Public Property tbMoedas_Simbolo As String
    Public Property tbMoedas_CasasDecimaisTotais As Nullable(Of Byte)

End Class
