'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwMapaCaixa
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property CodigoFormaPagamento As String
    Public Property DescricaoFormaPagamento As String
    Public Property CodigoContaCaixa As String
    Public Property DescricaoContaCaixa As String
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDTipoDocumentoSeries As Nullable(Of Long)
    Public Property NumeroDocumento As String
    Public Property Utilizador As String
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Documento As String
    Public Property TipoMovimento As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property Ativo As Boolean
    Public Property Natureza As String
    Public Property TotalMoeda As Nullable(Of Double)
    Public Property TotalMoedaReferencia As Nullable(Of Double)
    Public Property Saldo As Double
    Public Property tbMoedas_Descricao As String
    Public Property tbMoedas_Simbolo As String
    Public Property tbMoedas_CasasDecimaisTotais As Nullable(Of Byte)
    Public Property tbMoedas_TaxaConversao As Nullable(Of Double)
    Public Property IDLoja As Nullable(Of Long)
    Public Property IDFormaPagamento As Nullable(Of Long)
    Public Property IDContaCaixa As Long
    Public Property IDDocumento As Nullable(Of Long)
    Public Property ID As Long

End Class
