'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwMapaPendentesCompras
    Public Property ID As Nullable(Of Long)
    Public Property IDLoja As Nullable(Of Long)
    Public Property NomeFiscal As String
    Public Property IDEntidade As Nullable(Of Long)
    Public Property IDTipoDocumento As Nullable(Of Long)
    Public Property IDTiposDocumentoSeries As Nullable(Of Long)
    Public Property NumeroDocumento As Nullable(Of Long)
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Utilizador As String
    Public Property Documento As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property Ativo As Nullable(Of Boolean)
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property CodigoFornecedor As String
    Public Property NContribuinte As String
    Public Property CodigoTipoDocumento As String
    Public Property DescricaoTipoDocumento As String
    Public Property DescricaoTipoDocumentoSerie As String
    Public Property CodigoNatureza As String
    Public Property Natureza As String
    Public Property Valor As Double
    Public Property ValorPendente As Double
    Public Property Pago As Boolean
    Public Property Saldo As Double
    Public Property tbMoedas_Simbolo As String
    Public Property tbMoedas_CasasDecimaisTotais As Nullable(Of Byte)
    Public Property NumeroDias As Nullable(Of Integer)
    Public Property Valornumcasasdecimais As Nullable(Of Byte)
    Public Property ValorPendentenumcasasdecimais As Nullable(Of Byte)
    Public Property Saldonumcasasdecimais As Nullable(Of Byte)
    Public Property NumeroDiasnumcasasdecimais As Integer

End Class
