'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwMapaRankingVendas
    Public Property CodigoCliente As String
    Public Property NomeFiscal As String
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property CodigoMarca As String
    Public Property DescricaoMarca As String
    Public Property CodigoTipoArtigo As String
    Public Property DescricaoTipoArtigo As String
    Public Property CodigoArtigo As String
    Public Property DescricaoArtigo As String
    Public Property CodigoLote As String
    Public Property DescricaoLote As String
    Public Property CodigoFornecedor As String
    Public Property DescricaoFornecedor As String
    Public Property CodigoCampanha As String
    Public Property DataDocumento As Nullable(Of Date)
    Public Property Utilizador As String
    Public Property IDMoeda As Nullable(Of Long)
    Public Property TaxaConversao As Nullable(Of Double)
    Public Property tbMoedas_Simbolo As String
    Public Property tbMoedas_CasasDecimaisTotais As Nullable(Of Byte)
    Public Property Quantidade As Nullable(Of Double)
    Public Property Valor As Nullable(Of Double)
    Public Property Desconto As Nullable(Of Double)
    Public Property Liquido As Nullable(Of Double)
    Public Property TotalValor As Nullable(Of Double)
    Public Property TotalCustoMedio As Nullable(Of Double)
    Public Property Valornumcasasdecimais As Nullable(Of Byte)
    Public Property Descontonumcasasdecimais As Nullable(Of Byte)
    Public Property Liquidonumcasasdecimais As Nullable(Of Byte)
    Public Property TotalValornumcasasdecimais As Nullable(Of Byte)
    Public Property TotalCustoMedionumcasasdecimais As Nullable(Of Byte)

End Class
