'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vwStokArtigos
    Public Property CodigoArtigo As String
    Public Property DescricaoArtigo As String
    Public Property CodigoTipoArtigo As String
    Public Property DescricaoTipoArtigo As String
    Public Property CodigoFornecedor As String
    Public Property DescricaoFornecedor As String
    Public Property CodigoArmazem As String
    Public Property DescricaoArmazem As String
    Public Property CodigoArmazemLocalizacao As String
    Public Property DescricaoArmazemLocalizacao As String
    Public Property CodigoLote As String
    Public Property DescricaoLote As String
    Public Property CodigoLoja As String
    Public Property DescricaoLoja As String
    Public Property Medio As Double
    Public Property UltimoPrecoCusto As Double
    Public Property UltimoPrecoCompra As Double
    Public Property Quantidade As Nullable(Of Double)
    Public Property QuantidadeStock As Nullable(Of Double)
    Public Property UltimaEntrada As Nullable(Of Date)
    Public Property UltimaSaida As Nullable(Of Date)
    Public Property CodigoBarras As String
    Public Property Taxa As Nullable(Of Decimal)
    Public Property CodigoMarca As String
    Public Property DescricaoMarca As String
    Public Property IDModelo As Nullable(Of Long)
    Public Property CodigoCor As String
    Public Property Tamanho As String
    Public Property Hastes As String
    Public Property PotenciaCilindrica As Nullable(Of Double)
    Public Property PotenciaEsferica As Nullable(Of Double)
    Public Property Diametro As String
    Public Property Adicao As Nullable(Of Double)
    Public Property PotenciaPrismatica As Nullable(Of Double)
    Public Property Eixo As Nullable(Of Integer)
    Public Property Raio As String
    Public Property CorLente As String
    Public Property CodigoModelo As String
    Public Property DescricaoModelo As String
    Public Property TipoLente As String

End Class
